# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:

# use pyright for static type checking
- repo: https://github.com/RobertCraigie/pyright-python
  rev: v1.1.370
  hooks:
  - id: pyright

# alternatively: use mypy for static type checking
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: 'v1.9.0'
#   hooks:
#   -   id: mypy

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
      types_or: [ python, pyi, jupyter ]
      # args: [ --fix ]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
    - id: gitleaks

# ensure that an up-to-date .env.example file is present
- repo: https://github.com/hija/clean-dotenv
  rev: v0.0.7
  hooks:
  -   id: clean-dotenv
