# Übergabe von Christian Anders an Mario

## Fragen an CA (Stand 2026-02-03)

[x] - wurden zu dem komplx. Systeme (statistik teile ) Teil Excel Blätter oder Übungen durchgeführt? Kenntlich machen wo im Skript
    a)  Pi_Worksheet
    b)  Galtonbrett_Worksheet
[x] - Pi Wassertropfenübung als schriftliche Aufgabenstellung vorhanden?

[x] - Komplexe System Ebene 1 oder Ebene 2 ? 1. determ bis 12. butterfly 12 Ebene 3?
Soll Ebene 1 sein
4. Gab es übungen zur Coderegel?






## Infos

**CA Ziel:**

2. Er wollte sehen, ob 8 Leute in 10 Wochen ein Umweltmonitoringsystem entwickeln können. 

"PE2 ist der Besenwagen, der hinter der PE1 hinterher fährt"

## PDF erzeugen

1.  HTML rendern
2.  über Chrome drucken und **Adobe PDF** drucken
3.  über Adobe PDF das PDF verkleinern


## Termine

2. Termine.qmd ist IST-Stand in Gantt Chart

<mark>Hier ggf. Tabelle draus machen, weil Anpassungsaufwand groß ist </mark>

3. Vorlesungen idR 2 Blöcke / Labore auf 3 Blöcke = 5SWS Mittelwert eingehalten

letzte Vorlesung vor Weihnachten: 

1.  2P Klausur Bonus, Pitch 2min
2.  weiteren Industriedesigner Lehrbeauftragten dazu holen,um ggf. dieses Projekt gestalterisch zu betreuuen.



## Exkursionen in PE1

### Klimaschrank

Temperaturkurve von -40 .. 80 Grad durchfahren

### 3D Scanner 

### EMV Kammer

[ ] - rausfinden was 

### 3D Druck

### Shaker - Schütteltest


## Praktikums-Wahl (Produkt)

- Umweltmonitoring System
- Radio
- intelligentes Planzenbewässerungssystem


### Umweltmonitoring System

In den 4 Abgaben gibt es auch eine Doku. 

Studenten haben ein GIT Repo, <mark>nochmal nachfragen und ggf. zeigen lassen </mark>

Labor 3 hat die meisten Unterlagen

### Inbetriebnahme



### Test von Sensoren

Lichtsensor hat sich so wie er verbaut war als nicht testbar rausgestellt.

Umweltqualifizierung Spec von Sensoren - Ist der Sensor qualifiziert für die Umgebung?

# TODOS

[ ] - Umweltmonitoring die Abgaben Dateien alle anschauen
[x] - Umweltmonitoring HW von CA entgegenzunehmen
[ ] - Umweltmonitoring Aufgabenstellung (Basis V-Modell) erarbeiten und aufschreiben
    Sensoren und Bestellliste (Maße) - Daraus CAD Modell bzw. Raumvorstellung
    PMU (Basis Carmens Vorlesung) / DMU -> Explosionszeichnung + Pitchen des Entwurfs (AIDA Konformer Kurzvortrag 120sec jeder 1x machen) + attraktives A0 Poster (Carmen: Farben / Schriftarten etc.) innerhalb dieser 120sec (Szenario ihr pitcht auf Abend der Technik/ oder Bonding Messe - Ziel ist es, einen Investor zu kriegen)
    -> Stückliste + Kostenkalkulation
Ziel ist das V-Modell umzusetzen (und ggf. mehrfach zu durchlaufen):
1. Ideenfindung
2. Entwurf
3. Prototyp
4. Testing

die 3 Wochen Sensorbestellzeit die gespart wird neuer Schwerpunkt wählen.

[ ] - Ein Set aus Sensoren bestellen, sodass das Monitoringsystem keinen Zeitverlust durch Wartezeiten (Fredi bestellen lassen) - nochmal mit Daniel diskutieren, welche Sensoren es sein können
[x] - 01_Budget_Bauteile_PE2.xlsx
[x] - Gerät teste, mit USB Spannungsversorgung / müsste sich mit WLAN verbinden und Uhrzeit 
[ ] - Carmen fragen, wenn NutzerInnenverhalten losgelöst ist, ob das geht
[ ] - Versuche in Labor 4 durchlesen und überlegen, wie das qualifiziert beim nächsten Mal getestet werden kann.
[ ] - Klimaschrank - Testreihe Temperatur / Feuchtigkeit / CO2 / Timen und mit Stadtmitte klären, dass man dort 1 Nachmittag 1 Test machen kann
[ ] - Powerbank -> Noch bestellen 
[ ] - Markus Schlipf + Johannes Vorlesungen für Anforderungen nutzen
[ ] - Wettbewerbsanalyse + Patentrecherche diskutieren und überlegen wie es in dem DEB Curriculum rein soll (mehr/weniger)
[ ] - Exkurs Patent + Gebrauchsmuster -> um 2 Spalten um Design und Geschmacksmuster erweitern
[ ] - Schalter von CA analysieren und prüfen, unsichtbar ist bei normalem **quarto render**
[ ] - Marco -> PDF erzeugen mit Inhaltsverzeichnis
[ ] - Chi Quadrat Test Würfeln Aufgabenstellung
[ ] - Pi Regentropfen Aufgabenstellung
[ ] - Kano Modell / Bewertungsmatrix / Anforderungen / Morph Kasten in PE1 schieben
[ ] - Umweltqualifizierung komplett in PE2 verschieben
[ ] - in PE1 Testing anteasern aber nur Grundlagen in Kurz

2,8" wurde verbaut, und hat Farbe aber kein Touch 
2,1" wurde nicht verbaut

## Varianten

a) Vorlesung weiterentwickeln und auf der Höhe der Zeit halten
b) Prototyp Umweltmonitoringsystem **immer weiter verbessern**
c) Prototyp - Umweltmonitoringsystem **jedes Mal neu bauen**
d) Anknüpfungspunkte zu Daniel / Johannes? 
e) 

## weitere Funktionen

1. WLAN Konfiguration über QR Code ggf. um das Gerät dynamisch mit WLAN zu verbinden
2. Helligkeitssensor
3. 


## Mario  IoT <-> PR2

 - Mario fokussiert dann die Spezifikation und den Test des Produktes, welches Sensoren + Selbstlernkurs

## Daniel IoT <-> PR2

- Daniel hat C-Programmierung eingeführt um auf Sensordaten zuzugreifen.
- Displayansteuerung mit LVGL
- Basis mit ESP32, weil Basis IoT Vorlesun


### Sicherstellung Studierbarkeit

Wenn man die umgekehrte Reihenfolge (erst PE2 und dann IoT hören will), dann

1. in IoT Selbstlernkurs (Videokurs + Grundlagenwissen) + Anrechnung Labore zur ESP32 C Programmierung (Sensor auslesen per I²C, Display ansteuern über LVGL, WLAN Konfiguration
2. Student muss Testat machen, Quellcode und ESP32 Demonstration wird von Daniel abgenommen
3. wenn Erfolgreich -> Anrechnung des ersten Testats (die ersten 2-3 Labortermine) für IoT

### Sensoren -> Input Daniel