---
title: "DEB3 Produktentwicklung 1"
format:
  html:
    theme: cosmo
    mermaid:
      theme: default
    embed-resources: true

author:
  - name: "Mario Rossdeutscher"
    roles: "Dozent"
    email: mario.rossdeutscher@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung *"Produktentwicklung 1"* für den Studiengang Digital Engineering DEB3
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
link-external-icon: true
link-external-newwindow: true


headlines:
  off: true
kommentare: 
  off : true
exercises:
  solutions:
  off: true
worksheets:
  off: true
---

<!-- -------------------------------------------------------------------------

                       Skriptum zur Vorlesung 25WS

-------------------------------------------------------------------------- -->

<!-- -------------------------------------------------------------------------

                       TODOs für nächstes Sem. 
                       1. Bedürfnis Thema in PE1 (Tabelle + RS Carmen + Digital Playbook)

-------------------------------------------------------------------------- -->



# Grundlagen {#sec-grundlagen}

## Technische Grundlagen


## Methodische Grundlagen


<!-- 00010-Projektmanagement-->

## Projektmanagement


<!-- -------------------------------------------------------------------------

                       Kapitel 2: Ideenfindung und Konzeptentwicklung

-------------------------------------------------------------------------- -->

<!-- 00051-Projektmanagement-->

# Ideenfindung und Konzeptentwicklung {#sec-ideenfindungundkonzept}

## Methodische Grundlagen

## Konzeptentwicklung und Entscheidungsfindung

    {{< include Lasten-_und_Pflichtenheft.qmd >}}

::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
ggf. woanders hinverschieben? logisch nicht korrekte Reihenfolge

::::
:::

<!-- -------------------------------------------------------------------------

                       Kapitel 3: Entwurfs- und Entwicklungsphase

-------------------------------------------------------------------------- -->


<!-- 00052-EntwurfundEntwicklung-->

# Entwurfs- und Entwicklungsphase {#sec-entwurfundentwicklung}


## NVH

## Kostenbeeinflussung im Produktentstehungsprozess

<!-- -------------------------------------------------------------------------

                       Kapitel 4: Prototyping und Test

-------------------------------------------------------------------------- -->

<!-- 00053-PrototypingundTest-->

# Prototyping und Test {#sec-prototypingundtest}


## Testing


<mark>Änderung für nächstes Sem! Hier nochmal Produktionskapitel anschauen </mark>

<!-- 00053-ProduktionsplanungundProduktion-->

# Produktionsplanung und Produktion {#sec-produktionsplanungundproduktion}


## Lean Production


<!-- -------------------------------------------------------------------------

                       Kapitel 6: Softskills

-------------------------------------------------------------------------- -->

<!-- 00054-Softskills alles in einen Ordner!-->

# Softskills - Zusammenarbeit und Selbstorganisation {#sec-softskills}

# Softskills - Arbeitsmethoden {#sec-softskills2}

<!-- -------------------------------------------------------------------------

                       Kapitel 7: Literatur

-------------------------------------------------------------------------- -->
# Literatur {#sec-literatur}
