project:
  type: website
  output-dir: release
lang: de

format: 
  html:
    self-contained: false
    code-overflow: wrap
    code-fold: true
    theme: cosmo
  pdf:
    documentclass: scrreprt

lightbox: true
search: false

toc: true
toc-title: "Table of Contents"
toc-float: true 
toc-depth: 4 

##number-sections: true

link-external-newwindow: true
link-external-icon: true

bibliography: references.bib

profile:
  group: 
    - [python-profile, cpp-profile, release-profile, wip-profile]
  default: release-profile

######################

#  pre-render: 
#  - setup.py