---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
---

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Produktentwicklung
  - AIDA-Modell

copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 6
link-external-icon: true
link-external-newwindow: true
-->



<!-- -------------------------------------------------------------------------

                       AIDA-Modell

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Softskills
:::

## AIDA-Modell {#sec-aida}

::: {.callout-tip}
## Definition: *"AIDA-Modell"*
[AIDA](https://de.wikipedia.org/wiki/AIDA-Modell) ist ein [Akronym](https://de.wikipedia.org/wiki/Akronym) für ein aufeinander aufbauendes Stufenmodell zur Werbewirksamkeit. Die Anfangsbuchstaben stehen für die englischen Begriffe **Attention**, **Interest**, **Desire** und **Action**.
:::

1. **Attention**: Die Aufmerksamkeit des Empfängers wird geweckt, etwa durch Plakate mit *"Eye Catchern"* oder personalisierter Ansprache.

2. **Interest**: Beim Empfänger der Werbung wird Interesse für eine Idee/das beworbene Produkt/die beworbene Dienstleistung geweckt. 

3. **Desire**: Beim Empfänger wird der Wunsch nach der Idee/dem Produkt/der Dienstleistung geweckt. Potentielle Einwände werden abgebaut und der Mehrwert der Idee/des Produkts/der Dienstleistung wird hervorgehoben.

4. **Action**: Der Empfänger wird zum weiteren Kennenlernen der Idee/dem Kauf des Produkts/dem Kauf der Dienstleistung bewogen (*"Call-to-Action"*). *"Call-to-Action"* kann auch die Bitte zur Fortsetzung des Gesprächs sein, z.B. im Rahmen einer weiteren, längeren Besprechung, ggf. auch in einem größeren Personenkreis.

::: {.callout-caution}
## Pro-Tipp!
Das AIDA-Modell ist hervorragend geeignet, um eine [Elevator Speech](https://de.wikipedia.org/wiki/Elevator_Pitch) im Rahmen der Phase Ideenfindung und Konzeptentwicklung des Produktentstehungsprozesses effektiv zu gestalten.
:::

::: {.callout-tip}
## Definition: *"Elevator-Speech/Elevator Pitch"*
[Elevator Speech](https://de.wikipedia.org/wiki/Elevator_Pitch) (auch "Elevator Pitch" genannt) ist eine kurze, überzeugende erste Präsentation einer Idee, eines Produkts oder einer Dienstleistung (*"Eine Idee pitchen."*).
:::

Der Kerngedanke einer [Elevator Speech](https://de.wikipedia.org/wiki/Elevator_Pitch) basiert auf dem Szenario, eine wichtige Person oder eine wichtige Funktion (z.B. den Projektleitenden) in einem Aufzug (oder der Warteschlange in der Kantine) "zufällig" zu treffen und diese dann während der Dauer einer Aufzugsfahrt (rund 90 Sekunden) für eine Idee/ein Produkt/eine Dienstleistung zu begeistern. 

::: {.callout-tip}
## Ziel der Elevator-Speech
Ziel der Elevator Speech ist es, die vorgestellte Idee/das vorgestellte Produkt/die vorgestellte Dienstleistung positiv besetzt im Gedächtnis der adressierten Person zu verankern.
:::

Ist die Idee/das Produkt/die Dienstleistung überzeugend genug vorgestellt worden, wird das Gespräch dann entweder direkt weitergeführt oder man verabredet sich zu einer weiterführenden Präsentation und Diskussion der vorgestellten Idee/des vorgestellten Produkts/der vorgestellten Dienstleistung. 

::: {.callout-caution}
## Pro-Tipp!
Das AIDA-Modell eignet sich auch hervorragend als Leitfaden zur Gestaltung von Postern für Messen oder Informationsveranstaltung, z.B. bei der Präsentation der Ergebnisse eigener Praktika, mechatronischer Prospekte oder der eigenen Bachelorarbeit. **Lange Textbausteine auf Postern dienen keinem der vier Stufen des AIDA-Modells und sind zu vermeiden.**

Wichtig ist **1.)** ein Bild (*"Eye Catcher"*), das die Aufmerksamkeit des Betrachters weckt, **2.)** eine kurze Beschreibung des Produkts/der Dienstleistung und **3.)** dessen/deren einzigartigen Vorteilen für den Adressaten^[Leitgedanke: *"Der Wurm muss dem Fisch schmecken, nicht dem Angler"* (Quelle: Unbekannt)] mittels weniger Schlagworte und optional zusätzlich einigen Grafiken oder Bildern sowie **4.)** die eigenen Kontaktdaten, z.B. in Form eines Data-Matrix-Codes mit Link auf eine Webseite oder eines einfach abzufotografierenden Datensatzes aus Ansprechpartner, E-Mail, Webadresse und ggf. Telefonnummer. 
:::
