---
title: "DEB3 Produktentwicklung 1"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Übungsaufgabe zur Vorlesung und Labor *"Produktentwicklung 1"* für den Studiengang Digital Engineering DEB3
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
  - Übungsaufgabe
  - Gantt-Diagramm
copyright: 
  holder: Christian Anders
  year: 2024
lang: de
bibliography: Literatur.bib
date: last-modified
toc: false
number-sections: false
scrollable: true
toc-location: right-body
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
---

<!--
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
-->

<!-- -------------------------------------------------------------------------

                       Aufgabe: Erstellen eines Gantt-Diagramms

-------------------------------------------------------------------------- -->

::: {.callout-note}
## Aufgabe: Gantt-Diagramm zur Prüfung "Produktentwicklung 1" (Dauer 20 min)

**Ausgangssituation**: An der Hochschule Esslingen findet im Wintersemester eine schriftliche Prüfung im Fach "Produktentwicklung 1" in DEB3 statt. Die Prüfung folgt der aktuellen SPO und den Vorgaben vom Prüfungsamt. Folgender Ablauf der Prüfung ist vorgesehen: 

10.3o h: Öffnen des Seminarraums durch den Dozenten und anschließendes Lüften des Raums für 15 Minuten. Parallel zum Lüften erfolgt bereits das Auslegen der Prüfungsvordrucke. Hierfür sind 10 Minuten vorgesehen. 

Das Verlesen des Prüfungsprotokolls wird 10 Minuten dauern und muss so rechtzeitig erfolgen, dass die Studierenden um 11.oo h mit dem Bearbeiten der Prüfungsvordrucke beginnen können. Das Verlesen des Prüfungsprotokolls erfolgt jedoch so spät als möglich um spät eintreffenden Studierenden ein möglichst großes Zeitfenster zur regulären Teilnahme an der Prüfung zu geben. 

Für das Bearbeiten der Prüfungsvordrucke steht den Studierenden 90 Minuten zur Verfügung. Unmittelbar danach erfolgt die Abgabe der bearbeiteten Prüfungsvordrucke (vorgesehen hierfür sind 5 Minuten) sowie in den folgenden 10 Minuten die Verabschiedung der Studierenden und schließlich das Schließen des Seminarraums durch den Dozenten. 

**Aufgabe**: Erstellen Sie das Gantt-Diagramm zum im Fallbeispiel geschilderten Ablauf der Prüfung. Tragen Sie zusätzlich zu allen mit einer Dauer versehenen Prozessen die Zeitpunkte des Öffnens und Schließens des Seminarraums sowie den Start und das Ende der Bearbeitung der Prüfungsvordrucke als Meilensteine ins Gantt-Diagramm ein.
:::

<!--
::: {.callout-important}
## Tipp! Prüfungsaufgaben bitte stets sehr sorgfältig lesen und alle gegebenen Informationen beachten!
:::
--> 

<!--
::: {.callout-tip collapse="true"} 
## Lösung: Gantt-Diagramm zur Prüfung "Produktentwicklung 1"
:::

```{mermaid}
%%| fig-width: 
%%| label: fig-label-gntuebungprüfungdeb3
%%| fig-cap: "Gantt-Diagramm zur Prüfung"
gantt
title Gantt-Diagramm zur Prüfung "Produktentwicklung 1"
    dateFormat HH:mm
    axisFormat %H:%M
    Öffnen des Seminarraums : milestone, m1, 10:30, 0m
    Lüften des Seminarraums : a1, after m1, 15m
    Auslegen der Prüfungsvordrucke : a2, after m1, 10m
    Verlesen des Prüfungsprotokolls : a3, 10:50, 10m
    Start der Bearbeitung der Prüfungsvordrucke : milestone, m2, 11:00, 0m
    Bearbeiten der Prüfungsvordrucke (Prüfung): a4, after m2, 90m
    Ende der Bearbeitung der Prüfungsvordrucke : milestone, m3, 12:30, 0m
    Abgabe der Prüfungsvordrucke: a5, after m3, 5m
    Verabschiedung der Studierenden: a6, after a5, 10m
    Schließen des Seminarraums: milestone, m4, after a6, 0m
```
-->

