Die Begriffe *"Holschuld"* und *"Bringschuld"* beziehen sich auf die Pflichten und Verantwortlichkeiten, bei einem Projekt insbesondere zwischen den verschiedenen Rollen einzelner Projektbeteiligter.

+ **Holschuld**: Eine [Holschuld](https://de.wikipedia.org/wiki/Holschuld#Informationsmanagement) liegt vor, wenn die Verantwortung für die Beschaffung oder Abholung bestimmter Leistungen oder Informationen beim Empfänger liegt. Das bedeutet, dass die Empfängerseite aktiv werden muss, um die gewünschten Leistungen oder Informationen einzufordern oder abzuholen. Hierbei ist der Projektteilnehmer dafür verantwortlich, die benötigten Ressourcen oder Ergebnisse aktiv anzufordern, sobald er sie benötigt.
+ **Bringschuld**: Eine [Bringschuld](https://de.wikipedia.org/wiki/Bringschuld#Informationsverwaltung) hingegen liegt vor, wenn die Verpflichtung zur Lieferung oder Erbringung von Leistungen oder Informationen bei der liefernden Partei liegt. Das bedeutet, dass die ausführende Seite die Verantwortung hat, die vereinbarten Leistungen oder Ergebnisse aktiv zu übergeben oder bereitzustellen, ohne dass die Empfängerseite dies explizit anfordern muss.


::: {.callout-tip}
## Wikipedia: *"Holschuld"*
Das Informationsmanagement benutzt die juristischen Begriffe Holschuld/Bringschuld für das Informationsverhalten von Personen oder Personal, das Informationen, Nachrichten oder Wissen vom Inhaber der Information rechtzeitig und vollständig und in geeigneter Form abzuholen oder an eine andere Person weiterzuleiten hat. Dabei haben Arbeitsanweisungen, Dienstanweisungen oder eine Führungskraft gemäß dem Sender-Empfänger-Modell vorab zu klären, für welche Informationen eine Holschuld (englisch pull) und für welche eine Bringschuld (englisch push) besteht und wer die Verantwortung für die Informationsübermittlung trägt. Eine Bringschuld liegt vor, wenn der Absender der Initiator der Informationsweiterleitung ist. Im Falle einer Holschuld ist der Empfänger der Initiator und muss sich selbst bemühen, eine Information von einer Quelle zu beziehen.
:::

::: {.callout-tip}
## Wikipedia: *"Bringschuld"*
Im betrieblichen Informationsmanagement wurde der Begriff Bringschuld aus dem Recht übernommen und bedeutet, dass eine Person im Rahmen ihres Informationsverhaltens verpflichtet ist, die ihr bekanntgewordenen relevanten Informationen rechtzeitig und umfassend und in geeigneter Form horizontal (gleichstufige Mitarbeiter) und/oder vertikal (Vorgesetzte) weiterzugeben, damit diese richtige Entscheidungen treffen können. Diese Bringschulden gibt es auf allen Hierarchieebenen. In diesem Zusammenhang ist auch von Berichtsebenen die Rede, bei denen ein Verantwortungsträger einem übergeordneten Verantwortungsträger gegenüber eine Berichtspflicht besitzt. Umgekehrt besitzen auch Vorgesetzte die Pflicht, die ihnen bekannt gewordenen Informationen – sofern sie nicht geheim sind – an Mitarbeiter weiterzugeben. Den gegenläufigen Informationsverlauf bezeichnet man entsprechend als Holschuld.
:::

In der Praxis werden Holschuld oder Bringschuld der verschiedenen Rollen in einem Projekt oftmals nicht explizit festgelegt. Eine klare Definition der Verantwortlichkeiten trägt jedoch maßgeblich zur reibungslosen Durchführung eines Projekts bei. Je nach Art des Projekts und den darin enthaltenen Rollen können dabei sowohl Holschuld als auch Bringschuld für verschiedene Phasen des Projekts gelten sich im Projektfortschritt auch umkehren.


::: {.callout-caution}
Die Erwartungshaltung bezüglich Hol- und Bringschuld sind durch die Projektleitung offen und spätestens zum Start des Projekts sowie ggf. bei Änderungen der Rollen bzw. der AKV für alle Projektbeteilige transparent kommunizieren. Hol- und Bringschuld sind wichtige Bestandteile der AKV aller Projektbeteiligten. Es muss zu jedem Zeitpunkt für alle Beteiligte klar sein, wer die Verantwortung für den Austausch der jeweiligen Leistungen oder Informationen hat.
:::