---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
---

<!-- -------------------------------------------------------------------------

                       KRITISCHER PFAD

-------------------------------------------------------------------------- -->


### Kritischer Pfad {#sec-kritischerpfad}


::: {.callout-tip}
## Definition: *"Kritischer Pfad"*
Der "kritische Pfad" bezeichnet die kürzestmögliche Abfolge von miteinander verbundenen Aufgaben in einem Projekt, die die Gesamtdauer eines Projekts bestimmt. Der kritische Pfad repräsentiert die kürzeste mögliche Dauer, in der das Projekt abgeschlossen werden kann, wenn keine Verzögerungen auftreten. Jede Verzögerung auf dem kritischen Pfad führt zu einer Verlängerung der Gesamtdauer des Projekts. Der kritische Pfad wird durch die Abhängigkeiten zwischen den Aufgaben sowie durch die Dauer jeder Aufgabe bestimmt.
:::

Der kritische Pfad identifiziert diejenigen Aufgaben, deren Verzögerung den Gesamtzeitplan des Projekts verzögern würde. Jede Aktivität auf dem kritischen Pfad hat eine Nullpufferzeit, was bedeutet, dass Verzögerungen in diesen Aktivitäten zwangsläufig zu Verzögerungen des gesamten Projekts führen würden. 

::: {.callout-caution}
## kritischen Pfad managen!
Das Management des kritischen Pfads ist von entscheidender Bedeutung, um sicherzustellen, dass das Projekt gemäß Zeitplan und Budget abgeschlossen wird.
:::


Ein Beispiel für die Darstellung des kritischen Pfads in einem Gantt-Diagramm zeigt @fig-label-gntmermaid. Der kritische Pfad ist in dem Gantt-Diagramm rot gekennzeichnet dargestellt.

Die Identifizierung des kritischen Pfads ist entscheidend für das Projektmanagement, da er Aufgabenpriorisierung, Ressourcenallokation und Zeitplanung beeinflusst. Durch die Fokussierung auf den kritischen Pfad können Projektmanager*innen potenzielle Engpässe und Risiken identifizieren und Maßnahmen ergreifen, um sicherzustellen, dass das Projekt rechtzeitig und innerhalb des Budgets abgeschlossen wird.

Ein Projekt kann auch mehrere kritische Pfade haben, insbesondere in komplexen Projekten mit vielen Aufgaben und Abhängigkeiten. Die sorgfältige Analyse des kritischen Pfads ist daher eine fortlaufende Aufgabe im Projektmanagement, um den Projektverlauf zu überwachen und mögliche Verzögerungen frühzeitig zu erkennen und anzugehen.

Durch die Analyse des kritischen Pfads kann das Projektmanagementteam Prioritäten setzen und (ggf. zusätzliche) Ressourcen entsprechend zuweisen, um sicherzustellen, dass die Aktivitäten auf dem kritischen Pfad rechtzeitig abgeschlossen werden. Durch die Überwachung des kritischen Pfads können potenzielle Verzögerungen frühzeitig erkannt und entsprechende Maßnahmen ergriffen werden, um sicherzustellen, dass das Projekt innerhalb des geplanten Zeitrahmens abgeschlossen wird.

Der kritische Pfad kann mithilfe der folgenden Schritte identifiziert werden:

1. **Erstellen eines Netzplans**: Zeichnen Sie einen Netzplan^[Ein Netzplan im Projektmanagement ist eine allgemeine grafische Darstellung der Aktivitäten eines Projekts, die in Form von Knoten (auch als Ereignisse bezeichnet) und Pfeilen (auch als Aktivitäten oder Vorgänge bezeichnet) dargestellt werden. Der Netzplan visualisiert die zeitliche Abfolge und Abhängigkeiten der einzelnen Aktivitäten und ermöglicht es, den kritischen Pfad und die Gesamtdauer des Projekts zu bestimmen.
], das die verschiedenen Aktivitäten und deren Abhängigkeiten im Projekt visualisiert. Diese Darstellung dient als Grundlage für die Identifizierung des kritischen Pfads. 

::: {.callout-tip}
In der Regel erfolgt die Darstellung des Netzplans in Form eines Gantt-Diagramms.
:::

2. **Schätzung der Aktivitätsdauern**: Ermitteln Sie die geschätzte Dauer jeder Aktivität im Projekt. Die Dauer wird in realer Zeit gemessen, z.B. in der Anzahl von Arbeitstagen oder Wochen, die von Start der Aktivität bis zum Abschluss der Aktivität vergehen. Hierbei ist es wichtig, realistische und fundierte Schätzungen zu verwenden, um die Genauigkeit der Ergebnisse zu gewährleisten. Die Dauer der Aktivität steht dabei in keinem direkten Zusammenhang zu den für das Abarbeiten der Aktivität erforderlichen Ressourcen. Bei der Schätzung der Dauer der Aktivität sind jedoch die Randbedingungen wie z.B. tatsächlich verfügbare Ressourcen, Arbeitszeitmodelle usw. zu berücksichtigen.

3. **Bestimmung der Abhängigkeiten**: Identifizieren Sie die Abhängigkeiten zwischen den verschiedenen Aktivitäten im Projekt. Dadurch können Sie die Reihenfolge festlegen, in der die Aktivitäten durchgeführt werden müssen bzw. können. Zu den Abhängigkeiten gehören u.a. kausale Zusammenhänge (*"Aktivität B kann erst starten wenn Aktivität A abgeschlossen ist"*), aber auch Verfügbarkeit von Ressourcen (*"Die für die Tests zur Umweltqualifizierung notwendige große Klimakammer steht erst ab Juli kommenden Jahres zur Verfügung"*) oder auch Begrenzungen durch limitierte Ressourcen (*"Die für die Aktivität A und die Aktivität B notwendige Fachexpertin kann nicht zeitgleich Aktivität A und Aktivität B bearbeiten"*).

4. **Berechnung der frühesten und spätesten Start- und Endzeiten**: Anhand des Abhängigkeiten und Dauern aller Aktivitäten können Sie die frühesten und spätesten Start- und Endzeiten für jede Aktivität im Projekt bestimmen.

::: {.callout-tip}
Oftmals können Aktivitäten beschleunigt oder parallel abgearbeitet werden wenn es dem Projektmanagement gelingt, mehr und vor allem die richtigen Ressourcen für das Projekt zu gewinnen (siehe @sec-magischesdreieck → Magisches Dreieck des Projektmanagements) 
:::

5. **Berechnung der Pufferzeiten**: Berechnen Sie die Pufferzeiten für jede Aktivität, um festzustellen, welche Aktivitäten Spielraum für Verzögerungen haben, ohne den Gesamtzeitplan zu gefährden.

6. **Identifizierung des kritischen Pfads**: Der kritische Pfad besteht aus derjenigen Abfolge von Aktivitäten, die keine Pufferzeit haben und daher den Gesamtzeitplan des Projekts bestimmen. Identifizieren Sie diejenigen Aktivitäten, die auf dem kritischen Pfad liegen, um zu bestimmen, welche Aufgaben entscheidend für den Abschluss des Projekts innerhalb des Zeitrahmens sind und im Zentrum der Aufmerksamkeit des Projektmanagements stehen müssen um Verzögerungen zu vermeiden.

::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
\@mrossde Übung zum krit. Pfad mit Ganttproject vorbereiten?

::::
:::