---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib


headlines:
  off: true
extended-content:
  off: false
included-content:
  off: false
worksheets:
  off: false
exercises:
  solutions:
    on: true 
fileformat-svg:
  off: true
---

<!--
headlines:
  off: true
extended-content:
  off: false
included-content:
  off: false
worksheets:
  off: true
-->

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Komplexe Systeme
  - Determinismus
  - Laplace'scher Dämon
  
copyright: 
  holder: Christian Anders
  year: 2026
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
-->

<!--
number-offset: 
0 Grundlagen
1 Ideenfindung und Konzeptentwicklung
2 Entwurfs- und Entwicklungsphase
3 Prototyping und Test
4 Produktionsplanung und Produktion
5 Softskills
6 Literatur 
7 Anhang
-->

<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

------------------------------------------------------------------------------ 

::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Grundlagen
## Komplexe Systeme
:::

<!-- -------------------------------------------------------------------------

                       Laplace'scher Dämon

-------------------------------------------------------------------------- -->

### Laplace'scher Dämon {#sec-laplacedaemon}

::: {.callout-tip}
## Definition *"Laplace'scher Dämon"*
Der [Laplace'scher Dämon](https://de.wikipedia.org/wiki/Laplacescher_D%C3%A4mon) ist die Veranschaulichung der erkenntnis- und wissenschaftstheoretischen Auffassung, nach der es im Sinne der Vorstellung eines geschlossenen mathematischen Weltgleichungssystems möglich ist, unter der Kenntnis sämtlicher Naturgesetze und aller Initialbedingungen wie Lage, Position und Geschwindigkeit aller im Kosmos vorhandenen physikalischen Teilchen, jeden vergangenen und jeden zukünftigen Zustand zu berechnen und zu determinieren. 
:::

--- 

>
*„Wir müssen also den gegenwärtigen Zustand des Universums als Folge eines früheren Zustandes ansehen und als Ursache des Zustandes, der danach kommt. Eine Intelligenz, die in einem gegebenen Augenblick alle Kräfte kennt, mit denen die Welt begabt ist, und die gegenwärtige Lage der Gebilde, die sie zusammensetzen, und die überdies umfassend genug wäre, diese Kenntnisse der Analyse zu unterwerfen, würde in der gleichen Formel die Bewegungen der größten Himmelskörper und die des leichtesten Atoms einbegreifen. Nichts wäre für sie ungewiss, Zukunft und Vergangenheit lägen klar vor ihren Augen.“* (Pierre-Simon Laplace, 1814)

---

Benannt ist der Dämon nach [Pierre-Simon Laplace](https://de.wikipedia.org/wiki/Pierre-Simon_Laplace), der das dem Dämon zugrundeliegende Gedankenexperiment im Jahr 1814 formulierte.

Erkenntnisse zur Berechnung des [Dreikörperproblems](https://de.wikipedia.org/wiki/Dreik%C3%B6rperproblem) (1888), Überlegungen aus der [Relativitätstheorie](https://de.wikipedia.org/wiki/Relativit%C3%A4tstheorie) (1905), der [Quantenmechanik](https://de.wikipedia.org/wiki/Quantenphysik) (1925) sowie der [Chaostheorie](https://de.wikipedia.org/wiki/Schmetterlingseffekt) (1963) zeigen, dass der von Laplace postulierte Dämon in der Praxis an Grenzen stoßen würde. Das zugrundeliegende Konzept des Laplace'schen Dämons bleibt von diesen Einwänden jedoch unberührt.