flowchart LR
  A[Hauptgruppen] --> B[Urformen]
  A --> C[Umformen]
  A --> D[Trennen]
  A --> E[Fügen]
  A --> F[Beschichten]
  A --> G[Stoffeigenschaften ändern]
  B --> H[Gießen]
  B --> I[Rapid Prototyping]
  C --> J[Walzen]
  C --> K[Pressen]
  C --> L[Biegen]
  D --> M[Fräsen]
  D --> N[Bohren]
  D --> O[Schleifen]
  E --> P[Schweißen]
  E --> Q[Kleben]
  E --> R[Schrauben]
  F --> S[Galvanisieren]
  F --> T[Lackieren]
  G --> U[Härten]
  G --> V[Glühen]
  