---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
headlines:
  off: true

extended-content:
  off: false
---

<!--
headlines:
  off: true
extended-content:
  off: false
worksheets:
  off: false
--->

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
  - Statistik
  - Stochastik
  - Multi-Moment-Aufnahme
  - Multimomenthäufigkeits-Studie

copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: false
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
-->


<!-- -------------------------------------------------------------------------

                       Multi-Moment-Aufnahme

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Grundlagen
:::

### Multi-Moment-Aufnahme {#sec-multimomentaufnahme}

::: {.callout-tip}
## Definition *"Multi-Moment-Aufnahme"*
Die Multi-Moment-Aufnahme, auch [Multimomenthäufigkeits-Studie](https://de.wikipedia.org/wiki/Multimoment-Studie), ist ein Verfahren zur direkten Informationsbeschaffung durch Beobachtungen in variierenden Zeitabständen. 
:::

Die Beurteilung der [Signifikanz](https://de.wikipedia.org/wiki/Statistische_Signifikanz) der erzielten Ergebnisse erfolgt mithilfe der [Statistik](https://de.wikipedia.org/wiki/Statistik). Die Beurteilung der Wahrscheinlichkeiten erfolgt mithilfe der [Stochastik](https://de.wikipedia.org/wiki/Stochastik) (Wahrscheinlichkeitsrechnung).

```{mermaid}
%%| label: fig-label-mmzielemultimomentaufnahme
%%| fig-cap: "Mindmap der Anwendungen von Multi-Moment-Aufnahmen bei technischen Systemen"
%%{init: {'theme': 'forest'}}%%
mindmap
  root((Multi-Moment-Aufnahme))
    (Systemnutzung erfassen)
      (Betriebszustände dokumentieren)
      (Nutzungsmuster erkennen)
    (Effizienzsteigerung)
      (Engpässe identifizieren)
      (Prozessoptimierung ableiten)
    (Fehler- und Störungsanalyse)
      (Ursachen von Ausfällen erkennen)
      (Korrelationen zwischen Ereignissen erkennen)
    (Ressourcennutzung analysieren)
    (Wartungsstrategie verbessern)
      (Predictive Maintenance unterstützen)
      (Wartungsintervalle anpassen)
    (Automatisierungspotenziale identifizieren)
      (Manuelle Eingriffe analysieren)
      (Optimierungsmöglichkeiten für Steuerungen)
```

::: {.callout-important}
## Anforderungen bei Multi-Moment-Aufnahmen
Die Zeitpunkte bei Multi-Moment-Aufnahmen müssen 1.) **zufällig** sein, es müssen 2.) **hinreichend viele** einzelne Aufnahmen erfolgen und 3.) die Multi-Moment-Aufnahme muss über einen **hinreichend langen Zeitraum** durchgeführt werden. 
:::

Wie viele Aufnahmen hinreichend und welcher Zeitraum hinreichend ist hängt dabei vom betrachteten System und der benötigten Zuverlässigkeit der Multi-Moment-Aufnahmen ab. 

::: {.callout-warning}
## Für die Ausgestaltung von Multi-Moment-Aufnahmen ist Vorwissen über das System erforderlich!
Die Ausgestaltung einer Multi-Moment-Aufnahme setzt daher stets Vorwissen oder zumindest A-Priori-Wissen über das zu untersuchende System voraus.  
:::

::: {.callout-tip}
## Definition *"A-Priori-Wissen"*
[A-Priori](https://de.wikipedia.org/wiki/A_priori)-Wissen ist Wissen, das unabhängig von Erfahrung erlangt wird und auf reinem Denken oder logischer Analyse beruht.
:::


<!-- --------------------------------------------------------------------------
EXTENDED CONTENT  -  EXTENDED CONTENT  -  EXTENDED CONTENT  -  EXTENDED CONTENT
S T A R T ---
::: {.content-visible unless-meta="extended-content.off"}
<!-- ---------------------------------------------------------------------- -->

::: {.callout-note}
## Exkurs: Nyquist-Shannon-Abtasttheorem

{{< include Abbildung_Shannon.qmd >}}

Das [Nyquist-Shannon-Abtasttheorem](https://de.wikipedia.org/wiki/Nyquist-Shannon-Abtasttheorem), formuliert von [Claude Shannon](https://de.wikipedia.org/wiki/Claude_Shannon) basierend auf Arbeiten von [Harry Nyquist](https://de.wikipedia.org/wiki/Harry_Nyquistim) im Jahr 1948^[[Wladimir Kotelnikow](https://de.wikipedia.org/wiki/Wladimir_Alexandrowitsch_Kotelnikow) (* 6. September 1908; † 11. Februar 2005) formulierte das Abtasttheorem bereits 1933. Die Veröffentlichung in einem sowjetischen Konferenzbericht wurde im Osten seit den 1950er Jahren referenziert, blieb aber allgemein im Westen bis in die 1980er weitgehend unbekannt.], besagt, dass ein kontinuierliches Signal mit einer maximalen Frequenz $f_{max}$ vollständig und fehlerfrei rekonstruiert werden kann, wenn es mit einer Abtastfrequenz $f_{sample}$ von mindestens dem Doppelten dieser maximalen Frequenz, also 

$$
f_{sample} ≥ 2 \cdot f_{max}
$$ {#eq-nyquist_shannon}

abgetastet wird. 

**Die zentrale Aussage des Nyquist-Shannon-Abtasttheorems ist, dass bei einer hinreichenden Abtastrate und hinreichend langer Abtastung die gesamte Information des ursprünglichen Signals bei dessen Digitalisierung erhalten bleibt.** 

Das Nyquist-Shannon-Abtasttheorem ist eine der wichtigsten Grundlagen der [Signalverarbeitung](https://de.wikipedia.org/wiki/Signalverarbeitung) und [Informationstheorie](https://de.wikipedia.org/wiki/Informationstheorie).
:::


<!-- ---------------------------------------------------------------------- ---
:::
<!-- S T O P
EXTENDED CONTENT  -  EXTENDED CONTENT  -  EXTENDED CONTENT  -  EXTENDED CONTENT
--------------------------------------------------------------------------- -->



<!-- -------------------------------------------------------------------------

                       Weiterführende Links (Internet)

-------------------------------------------------------------------------- -->

::: {.callout-tip}
## Weiterführende Links (Internet)
+ [Multi-Moment-Aufnahme im Organisationsmanagement](https://www.orghandbuch.de/Webs/OHB/DE/OrganisationshandbuchNEU/2_Organisationsmanagement/2_4_Ressourcen/2_4_3_Leitfaden/2_4_3_11_Methoden%20der%20PBE/2_4_3_11_5_Multimomentaufnahme/Multimomentaufnahme-node.html) (Quelle: [Bundesministerium des Innern | Bundesverwaltungsamt](https://www.orghandbuch.de/Webs/OHB/DE/startseite/startseite-node.html))
:::
