---
title: "MTB3 Entwicklung mechatronischer Systeme 1"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    email: christian.anders@hs-esslingen.de
    affiliations: Hochschule Esslingen
date: last-modified
toc: false
number-sections: false
scrollable: true
---

<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
<!--
::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::
-->

### Pitch {#sec-pitch}


---

> *„Der Wurm muss dem Fisch schmecken, nicht dem Angler.“* (Quelle: Unbekannt)

---

::: {.callout-tip}
## Definition: *"Pitch"*
Ein [Pitch](https://en.wikipedia.org/wiki/Elevator_pitch) (auch *"Elevator Pitch"*, *"Elevator Speech"* oder (seltener) *"Elevator Statement"*) ist die Kunst, ein Projekt, eine Idee oder ein Produkt in kurzer Zeit (rund 60 Sekunden) auf überzeugende Weise zu präsentieren, um Interesse zu wecken, Unterstützung zu gewinnen oder Investoren, Kunden oder andere Stakeholder zu überzeugen (siehe → Golden Circle @sec-goldencircle, siehe → AIDA-Modell @sec-aida). 
:::

Der Elevator Pitch war ursprünglich eine Idee amerikanischer Mitarbeitenden des Vertriebs, die Kunden und Chefs während der Dauer einer Aufzugfahrt von ihrer Idee überzeugen wollten. Weil die Fahrt selten länger als 60 Sekunden dauerte, mussten alle relevanten Informationen in dieses Zeitfenster passen: Kurzvorstellung, Begeisterung für das Projekt wecken und den Auftrag an Land ziehen oder den vielbeschäftigten und daher in der Regel nicht erreichbaren Chef zu überzeugen.

---

> *"The goal is to convey the overall concept or topic being pitched in a concise and exciting way."*

---

Der Elevator Pitch war schon nach kurzer Zeit so erfolgreich, dass der *"Pitch"* ("*pitchen*") zum geflügelten Wort wurde und bis heute genutzt wird. Allerdings wird die Kurzpräsentation nur noch selten im Aufzug vorgetragen. 

::: {.callout-important}
## Pro-Tipp!
**Ziel es Pitches ist es heute in der Praxis zumeist, beim Adressaten des Pitches einen längeren Folgetermin zur dann umfangreicheren Vorstellung der Idee, des Projekts oder Produkts zu erhalten.**
:::

::: {.callout-caution}
## Pro-Tipp!
Das Vorbereiten eines Pitches (oder eines vergleichbaren Vortrags, z.B. auf einer Ausstellung oder bei einer Prüfung an der Hochschule) ist sehr zeitaufwendig und wird von unerfahrenen Vortragenden zumeist deutlich unterschätzt. Als Anhaltspunkt für die Vorbereitung von Vorträgen für Pitches, wichtigen Besprechungen, Workshops, Messen und Ausstellungen (wobei alle fachlichen Informationen als bereits vorliegend angenommen werden) gilt:

**Jede Minute Vortrag erfordert eine Stunde Vorbereitung.**

<!--
<p style="text-align:center;">**Jede Minute Vortrag erfordert eine Stunde Vorbereitung.**</p>
-->

In einzelnen Fällen (z.B. der Präsentation der eigenen Doktorarbeit im Rahmen eines Vortrags bei der Dissertationsprüfung oder der Selbstvorstellung im Rahmen eines [Assessment Centers](https://en.wikipedia.org/wiki/Assessment_centre)) kann der Aufwand für einen Pitch oder einen Vortrag auch deutlich mehr als das 10-fache der Dauer des Vortrags oder Pitches betragen!
:::


<!--
Um ein Projekt erfolgreich zu pitchen, gibt es einige Regeln deren Beachtung helfen kann, den Pitch erfolgreich zu gestalten:

1. Kenne dein Publikum“: Falls möglich: Recherchieren Sie im Voraus, wer Ihre Zuhörer sein werden. Verstehen Sie die Interessen, Bedürfnisse und Erwartungen Ihres Publikums, damit Sie Ihre Präsentation entsprechend anpassen können. Passen Sie Ihre Sprache, Ihre Beispiele und Ihre Argumente an, um eine Verbindung zu ihnen herzustellen und sie besser zu überzeugen.
1. Formulieren Sie eine klare und prägnante Botschaft: Formulieren Sie eine klare und prägnante Botschaft, die den Kern Ihres Projekts vermittelt. Vermeiden Sie Fachjargon oder zu komplexe Ausdrücke. Konzentrieren Sie sich darauf, den Wert und den Nutzen Ihres Projekts auf einfache und überzeugende Weise zu kommunizieren.
1. Nutzen Sie Storytelling: Verwenden Sie Storytelling-Elemente, um Ihre Präsentation lebendiger und ansprechender zu gestalten. Erzählen Sie eine Geschichte, die das Problem oder die Herausforderung aufzeigt, die Ihr Projekt lösen soll, und zeigen Sie auf, wie Ihr Projekt einen positiven Einfluss hat. Geschichten können emotional ansprechend sein und das Publikum dazu bringen, sich stärker mit dem Projekt zu identifizieren. 
1. Nutzen Sie visuelle Unterstützung: Nutzen Sie visuelle Hilfsmittel wie Präsentationsfolien, Grafiken oder Demos, um Ihre Präsentation zu unterstützen. Verwenden Sie ansprechendes Design und sorgen Sie für eine klare und verständliche Darstellung der Informationen. Visuelle Elemente können dabei helfen, komplexe Konzepte zu veranschaulichen und das Verständnis und die Aufmerksamkeit des Publikums zu erhöhen. 
1. Zeigen Sie Herausforderungen und Lösungen auf: Zeigen Sie auf, welche Herausforderungen oder Probleme Ihr Projekt angeht, und präsentieren Sie überzeugende Lösungen. Betonen Sie den Mehrwert und die Vorteile, die Ihr Projekt bietet, und erklären Sie, wie es zu einer positiven Veränderung oder Verbesserung führen kann.
1. Erklären Sie die praktische Umsetzung: Veranschaulichen Sie, wie Ihr Projekt praktisch umgesetzt wird und welchen konkreten Nutzen es bringt. Geben Sie einen Überblick über den Projektplan, die Meilensteine und die Zeitrahmen. Zeigen Sie auf, wie das Projekt in den bestehenden Kontext oder die Organisation integriert wird und welche Ressourcen dafür benötigt werden. 
1. Beantworten Sie Fragen und Einwände: Bereiten Sie sich darauf vor, mögliche Fragen oder Einwände seitens des Publikums zu beantworten. Überlegen Sie im Voraus, welche Bedenken oder Zweifel auftreten könnten, und entwickeln Sie klare und überzeugende Antworten. Seien Sie bereit, Ihre Argumente zu verteidigen und weitere Informationen zu liefern, um Vertrauen und Glaubwürdigkeit aufzubauen. 
1. Zeigen Sie Begeisterung und Überzeugung: Seien Sie leidenschaftlich und überzeugt von Ihrem Projekt. Übertragen Sie Ihre Begeisterung auf das Publikum und zeigen Sie, dass Sie voll und ganz hinter Ihrem Projekt stehen. Emotionen können eine starke Rolle spielen, um andere zu inspirieren und zu motivieren, sich für Ihr Projekt zu engagieren.
1. Üben Sie und bereiten Sie sich vor: Üben Sie Ihre Präsentation gründlich im Voraus, um sicherzustellen, dass Sie sie selbstbewusst und flüssig vortragen können. Achten Sie auf Ihre Körpersprache, Ihre Stimme und Ihre Ausdrucksweise. Seien Sie gut vorbereitet, um einen professionellen und überzeugenden Eindruck zu hinterlassen.
1. Führen Sie ein Follow-up durch: Vergessen Sie nicht, nach dem Pitch einen Follow-up zu machen. Bedanken Sie sich für die Zeit und das Interesse des Publikums und bieten Sie weitere Informationen oder Unterstützung an, falls benötigt. Halten Sie den Kontakt aufrecht und bleiben Sie offen für weitere Gespräche oder Diskussionen.
-->