<!--
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
-->

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Produktentstehungsprozess
  - Poka-Yoke

copyright: 
  holder: Christian Anders
  year: 2026
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 2
link-external-icon: true
link-external-newwindow: true
-->

<!--
number-offset: 
0 Grundlagen
1 Ideenfindung und Konzeptentwicklung
2 Entwurfs- und Entwicklungsphase
3 Prototyping und Test
4 Produktionsplanung und Produktion
5 Softskills
6 Literatur 
7 Anhang
-->


<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
<!--
::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::
-->


<!-- -------------------------------------------------------------------------

                       Poka Yoke (Methode des Toyota-Produktionssystems)

-------------------------------------------------------------------------- -->

### Poka Yoke {#sec-poka-yoke}

::: {.callout-tip}
## Definition: *"Poka Yoke"*
Der japanische Ausdruck [Poka Yoke](https://de.wikipedia.org/wiki/Poka_Yoke) (dt. *"unglückliche Fehler vermeiden"*) bezeichnet ein aus mehreren Elementen bestehendes Prinzip, welches technische Vorkehrungen bzw. Einrichtungen zur präventive Fehlerverhinderung und zur sofortigen Fehleraufdeckung umfasst. 
:::

*"Poka"* bezeichnet einen falschen Zug im japanischen Brettspiel [Go](https://de.wikipedia.org/wiki/Go_(Spiel)) und im weiteren Sinne *"dumme Fehler, Schnitzer"* allgemein. *"Yoke"* bedeutet *"vermeiden"*.


Als Erfinder des Poka-Yoke-Prinzips gilt der Ingenieur [Shigeo Shingō](https://de.wikipedia.org/wiki/Shigeo_Shing%C5%8D). Der Ausgangspunkt für die Entwicklung des Poka-Yoke-Prinzips mit Fehlerquellen-Inspektion lag für Shingō bei der [statistischen Qualitätskontrolle (SQC)](https://de.wikipedia.org/wiki/Qualit%C3%A4tspr%C3%BCfung). Shingō stellte fest: 

---

>
*"Fehler werden in der Arbeitsphase erzeugt, und Qualitätsprüfungen können nichts anderes bewirken, als die Fehler zu finden."* ([Shigeo Shingō](https://de.wikipedia.org/wiki/Shigeo_Shing%C5%8D))

---

::: {.callout-tip}
## Pro-Tipp!
**Mit Poka Yoke wird durch meist einfache, aber wirkungsvolle technische Systeme dafür gesorgt, dass Fehlhandlungen im Produktionsprozess nicht zu Fehlern am Endprodukt führen.**
:::

Beispiele für das Poka-Yoke-Prinzip finden sich überall im Alltag: Bankautomaten in Deutschland geben das Geld oder den gedruckten Kontoauszug erst heraus, wenn die Karte aus dem Automaten entnommen wurde. Dadurch wird verhindert, dass die Karte vergessen wird. Beim Tanken passt die Zapfpistole für Diesel nicht in den Tankstutzen für Benzin. Dadurch wird verhindert, dass bei Benzinfahrzeugen der falsche Treibstoff getankt wird (***"Schlüssel-Schloss-Prinzip"***).

::: {.callout-important}
## Poka-Yoke im Produktentstehungsprozess
Das Poka-Yoke-Prinzip ist ein in der Entwurfs- und Entwicklungsphase des Produktentstehungsprozesses zumeist sehr einfach im Produkt zu verwirklichender, aber wesentlicher Bestandteil und wichtiger Erfolgsfaktor des [Toyota-Produktionssystem (TPS)](https://de.wikipedia.org/wiki/Toyota-Produktionssystem). In diesem Sinne ist Poka Yoke nicht nur ein Baustein des Qualitätsmanagements in der (Serien-)Produktion, sondern auch ein wichtiger Baustein der → **Produktionsgerechten Produktgestaltung** (PPG) @sec-ppg.
:::
