---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
---

<!--
title: "DEB3 Produktentwicklung 1"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung 1"* für den Studiengang Digital Engineering DEB3 im Wintersemester 2024/2025
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
  - Projekt
  - Projektziel
  - DoD
  - Projektphasen
  - Moving Targets
  - AKV
  - Weisungs- und Entscheidungsbefugnis
  - Integrity
  - Compliance
  - Geist des Vertrags
copyright: 
  holder: Christian Anders
  year: 2024
lang: de
bibliography: Literatur.bib
date: last-modified
toc: false
number-sections: false
scrollable: true
toc-location: right-body
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
-->


<!-- -------------------------------------------------------------------------

                       PROJEKT

-------------------------------------------------------------------------- -->

### Projekt {#sec-projekt}

::: {.callout-warning}
*"The first step of any project is to grossly underestimate its complexity and difficulty." ([Nicoll Hunt](https://x.com/nicollhunt))*
:::

#### Eigenschaften eines Projekts

Auch wenn ständig und nahezu überall von Projekten gesprochen wird, ist der Begriff *"Projekt"* nicht ganz einfach zu fassen:

::: {.callout-tip}
## Versuch einer Definition: *"Projekt"*
Ein Projekt ist eine zeitlich begrenzte und organisierte Anstrengung, die darauf abzielt, ein bestimmtes Ziel zu erreichen. Es handelt sich um eine eindeutig definierte Aufgabe oder eine Reihe von Aufgaben, die einen spezifischen Anfangs- und Endpunkt haben. Projekte werden in der Regel durchgeführt, um einzigartige Produkte, Dienstleistungen oder Ergebnisse zu schaffen und beinhalten eine Reihe von geplanten Aktivitäten, Ressourcen und Einschränkungen. Projekte zeichnen sich durch ihre Einmaligkeit, Komplexität und Zielorientierung aus. Projekte erfordern in der Regel eine Projektorganisation, eine klare Definition von Aufgaben und Verantwortlichkeiten, sowie ein effektives [Projektmanagement](https://de.wikipedia.org/wiki/Projektmanagement), um das gewünschte Ergebnis innerhalb der vorgegebenen Zeit, Kosten und Qualität zu erreichen.
:::

Der Begriff des Projekts ist darüber hinaus in der Literatur auf vielfältige Weise teilweise mit anderen Schwerpunkten definiert:

- „Eine sachlich und zeitlich begrenzte Aufgabe, die interdisziplinär angegangen wird.“
- „Ein zeitlich definiertes und begrenztes Vorhaben mit dem Ziel, ein einmaliges Produkt, eine Dienstleistung oder ein Ergebnis zu schaffen.“ (Quelle: PMBOK Guide des amerikanischen Project Management Institute)
- „Vorhaben, das im Wesentlichen durch die Einmaligkeit aber auch Konstante der Bedingungen in ihrer Gesamtheit gekennzeichnet ist, wie z.B. Zielvorgabe, zeitliche, finanzielle, personelle und andere Begrenzungen; Abgrenzung gegenüber anderen Vorhaben; projektspezifische Organisation.“ [Quelle: DIN 69901 des Deutschen Instituts für Normung e.V.]
- Eine für einen befristeten Zeitraum geschaffene Organisation, die den Auftrag hat, mindestens ein Produkt entsprechend einem vereinbarten Business Case zu liefern.“
- „Ein Projekt ist ein einmaliges, zeitlich befristetes, interdisziplinäres, organisiertes Vorhaben, um festgelegte Arbeitsergebnisse im Rahmen vorab definierter Anforderungen und Rahmenbedingungen zu erzielen.“ (Quelle: IPMA ICB 4.0 der International Project Management Association)

::: {.callout-tip}
Eine Aufgabenstellung kann und sollte in der Regel als Projekt betrachtet werden, sofern das zu lösende Problem relativ komplex erscheint, der Lösungsweg zunächst unbekannt ist, eine Zielrichtung und ein Zeitrahmen vorliegen und/oder bereichs-/fachübergreifende Zusammenarbeit erforderlich ist.
:::

Die Komplexität der Aufgabenstellung liegt beispielsweise darin, dass:

- es eine Vielzahl von Lösungswegen gibt, deren Erfolg zu Projektbeginn unbekannt ist,
- das Ziel bei genauer Analyse widersprüchliche Teilziele enthält (Zielkonflikte),
- die involvierten bzw. zusammenarbeitenden Organisationen oder Instanzen unterschiedlichen Sachlogiken gehorchen,
- zwischen den einzelnen Maßnahmen zur Zielerreichung vielfältige Wechselwirkungen bestehen.

In der Regel birgt ein Projekt – im Gegensatz zu regelmäßigen, stets ähnlich durchgeführten, weitgehend identischen Vorhaben – meist ein **höheres Risiko des Scheiterns** und wird in einer speziellen und befristeten Organisationsform, der so genannten Projektorganisation, abgewickelt, innerhalb derer auf das Ziel hingearbeitet wird.

#### Definition Projektziel
<!-- appearance="simple" -->
::: {.callout-tip}
## Definition: *"Projektziel"*
Ein Ziel ist ein angestrebter Zustand oder ein gewünschtes Ergebnis, das eine Person, eine Gruppe oder eine Organisation erreichen möchte. Es ist eine klare und spezifische Vorstellung von dem, was man erreichen möchte und dient als Leitfaden für Handlungen und Entscheidungen. Ziele können kurzfristig oder langfristig sein und helfen dabei, den Fokus, die Motivation und die Richtung für individuelle oder kollektive Bemühungen zu setzen. Sie dienen als Messlatte für den Fortschritt und ermöglichen es, den Erfolg zu bewerten und gegebenenfalls Anpassungen vorzunehmen, um das gewünschte Ergebnis zu erreichen. Das Ziel wird als Anlass für eine Handlung verstanden.

::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
\@mrossde ggf. mit der anderen Zieldefinition abgleichen und hier noch ein include?

::::
:::

:::

> *"Ziele sind Ursachen, die in der Zukunft liegen."*


::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
\@mrossde Bild mit Boot hier rein / auf Innitiierungsphase abgleichen
weiterhin -> Boot fährt erst los, wenn Projektauftrag erteilt ist
Auftraggeber ist am ufer und sitzt nicht im Boot und steuert. 
sonst ist der Projektleiter nutzlos/ machtlos

::::
:::

Projektziele sind die konkreten, messbaren Ergebnisse oder Leistungen, die ein Projekt erreichen soll. Im Gegensatz zu Meilensteinen, die wichtige Zeitpunkte oder Phasen während der Projektumsetzung markieren, beschreiben Projektziele die angestrebten Endresultate oder den gewünschten Zustand, der durch das Projekt erreicht werden soll.

Projektziele geben die Richtung und den Zweck des Projekts vor und definieren die Erfolgskriterien, anhand derer der Projektfortschritt bewertet wird. Sie sind spezifisch, messbar, erreichbar, relevant und zeitgebunden (SMART-Kriterien). Typischerweise werden Projektziele zu Beginn des Projekts festgelegt und dienen als Leitfaden für die Planung, Ausführung und Bewertung des Projekts.

Beispiele für Projektziele können sein:

1. Reduzierung der Produktionskosten um 15% im Vergleich zum Vorgängerprodukt.
2. Einhalten der vorgegebenen Ziele zu (reduziertem) Gewichts, (verringertem) Bauraum und (erhöhter)Leistung.
3. Markteinführung des neuen Produkts bis Ende des Geschäftsjahres.
4. Verbesserung der Kundenzufriedenheit mit dem neuen Produkt auf mindestens Platz 3 bei einem internationalen Ranking (z.B. [J.D. Power](https://www.jdpower.com/cars/ratings)).
5. Reduzierung der mit dem neue Produkt verbundenen Garantie- und Kulanzkosten um 20% gegenüber dem aktuellen Produkt.

Projektziele sind grundlegend für das Projektmanagement, da sie den Rahmen für die Planung und Ausführung des Projekts bilden. Sie helfen, sicherzustellen, dass das Projekt die beabsichtigten Ergebnisse liefert und den Bedürfnissen und Erwartungen der Stakeholder entspricht (siehe → @sec-smart SMARTe Ziele)

<!-- -------------------------------------------------------------------------

                       SMART

-------------------------------------------------------------------------- -->

**Wann waren wir erfolgreich?** 

::: {.callout-tip}
## Definition: *"Definition of Done (DoD)"*
Die „Definition of Done“ (DoD) ist eine festgelegte und akzeptierte Vereinbarung innerhalb eines Teams oder Projekts, die die Kriterien und Anforderungen beschreibt, die erfüllt sein müssen, damit eine Aufgabe, ein Feature oder ein Projekt als abgeschlossen gilt. Sie legt die Standards und Erwartungen fest, die erfüllt sein müssen, um sicherzustellen, dass ein Arbeitsergebnis vollständig ist. Die Definition of Done hilft sicherzustellen, dass alle Beteiligte ein gemeinsames Verständnis davon haben, was "fertig" bedeutet.
:::



Die nachfolgenden Überlegungen können helfen, ob ein vorgegebenes Ziel erfolgreich erreicht wurde:

- **Klar definierte Kriterien**: Stellen Sie sicher, dass das Ziel von Anfang an klar definiert wurde und messbare Kriterien beinhaltet (siehe → Vermeidung von "Moving Targets"). Dies ermöglicht es Ihnen, den Grad der Zielerreichung objektiv zu bewerten.
- **Überprüfen der Zielerreichung**: Vergleichen Sie den aktuellen Zustand oder das Ergebnis mit den definierten Kriterien des Ziels. Wenn alle Kriterien erfüllt sind, kann davon ausgegangen werden, dass das Ziel erreicht wurde.
- **Quantitative und qualitative Messungen**: Berücksichtigen Sie sowohl quantitative als auch qualitative Messungen, um den Erfolg des Ziels zu bewerten. Quantitative Messungen können beispielsweise Zahlen, Daten oder Metriken umfassen, während qualitative Messungen subjektivere Faktoren wie Kundenzufriedenheit oder Feedback berücksichtigen.

<!--  START DES FEHLERHAFTEN BEREICHS -->

---

> *"If you can't measure it, you can't manage it." ([Peter F. Drucker](https://de.wikipedia.org/wiki/Peter_Drucker))*

---

<!--  ENDE DES FEHLERHAFTEN BEREICHS -->

- **Zeitliche Komponente**: Stellen Sie sicher, dass das Ziel innerhalb des vorgegebenen Zeitrahmens erreicht wurde. Berücksichtigen Sie auch Zwischenziele oder Meilensteine, um den Fortschritt zu überwachen.
- **Bewertung durch die Auftraggeber**: Befragen Sie relevante Auftraggeber, um deren Meinung und Perspektive über die Zielerreichung einzuholen. Dies kann zusätzliche Einblicke und Bestätigung liefern.
- **Selbstreflexion**: Führen Sie eine selbstkritische Bewertung durch und überlegen Sie, ob das Ziel tatsächlich die gewünschten Ergebnisse oder Auswirkungen erzielt hat. Reflektieren Sie auch mögliche Lernerfahrungen oder Verbesserungspotenziale für zukünftige Ziele.

Die Definition der Zielerreichung kann von Ziel zu Ziel unterschiedlich sein kann. Der Haupterfolgsfaktor besteht darin, klare Kriterien festzulegen, die eine objektive Bewertung ermöglichen, und verschiedene Aspekte zu berücksichtigen, um ein umfassendes Bild des Erfolgs zu erhalten.


#### Phasen von Projekten

```{mermaid}
%%| label: fig-label-pep0
%%| fig-cap: "Phasen von Projekten"
flowchart TD

  A[a- Projektinitiierung]
    A --> B[b- Projektplanung]
    B --> C[c- Projektdurchführung]    
    C --> D[d- Projektabschluss]
  B -->E[e- Projektcontrolling]
  E -->D

```

a) **Initiierung**: In dieser Phase wird das Projekt identifiziert, die Ziele werden definiert, der Umfang wird abgesteckt und die Ressourcen werden zugewiesen. Ein Projektauftrag oder eine Projektskizze wird erstellt, um die Grundlage für das weitere Vorgehen zu legen.

a) **Planung**: Während dieser Phase werden detaillierte Pläne erstellt, um die Ziele des Projekts zu erreichen. Dies beinhaltet die Definition von Meilensteinen, die Festlegung von Aufgaben und Verantwortlichkeiten, die Ressourcenplanung, die Zeitplanung, das Risikomanagement und die Budgetierung.

a) **Durchführung**: In dieser Phase werden die im Plan festgelegten Aufgaben durchgeführt. Bei Produktentstehungsprojekten wird diese Phase oftmals als das eigentliche Projekt betrachtet, weil hier das spätere Produkt erarbeitet wird. Das inhaltlich arbeitende Team trifft sich in der Regel erst zum Start dieser zum ersten Mal, meist im Rahmen eines Kick-Off-Events. Mit dem Kick-off-Event startet auch der Teamentwicklungsprozess, ohne dass dies immer als eigene Aufgabe thematisiert wird. Während der Phase der Durchführung arbeiten die Teammitglieder an ihren zugewiesenen Aufgaben, Ressourcen werden eingesetzt, und der Fortschritt wird durch die Projektleitung, unterstützt vom Controlling, regelmäßig überwacht und der Projektverlauf dokumentiert. 

a) **Abschluss**: Sobald alle Ziele erreicht sind und das Projekt erfolgreich abgeschlossen ist, oder aber von Seiten des Managements der Abbruch des Projekts beschlossen wird, wird es offiziell beendet. Der Projektabschluss beinhaltet die Übergabe von Ergebnissen an den Auftraggeber, das Erstellen eines Projektberichts, das Dokumentieren von Lernpunkten und - bei erfolgreichem Projektabschluss und meist im Rahmen eines feierlichen Abschlussevents - das Feiern von Erfolgen. Auch die abschließende Bewertung des Projekts hinsichtlich seiner Effektivität und Effizienz gehört zu dieser Phase.

a) **Projektcontrolling**: Während des gesamten Projekts wird in einem nebenläufigen Prozess der Fortschritt überwacht, um sicherzustellen, dass er den geplanten Zielen und Zeitplänen entspricht. Änderungen im Projektumfang, Risiken oder Ressourcen werden identifiziert und bewertet. Anpassungen werden vorgenommen, um bestmöglich sicherzustellen, dass das Projekt erfolgreich abgeschlossen werden kann. Bei massiven Abweichungen zwischen Projektplanung und tatsächlicher Entwicklung des Projekts können Projekte auch jederzeit abgebrochen werden.

#### Phasen bei der Projektdurchführung

Die in @fig-label-pep0 dargestellte Projektphase "3. Projektdurchführung" gliedert sich wiederum in einzelne Phasen, wobei die genaue Struktur und Benennung dieser Phasen je nach Unternehmen und Industrie variieren kann:

```{mermaid}
%%| label: fig-label-pep02
%%| fig-cap: "Untergeordnete Phasen der Phase Projektdurchführung im Produktentstehungsprozess"
flowchart TD
    C1[3.1 Konzeptentwicklung und -validierung]
       --> C2[3.2 Entwurfs und Entwicklung]
    C2 --> C3[3.3 Prototyping und Test]
    C3 --> C4[3.4 Fertigungs- und Produktionsvorbereitung]
    C4 --> C5[3.5 Markteinführung und Vermarktung]
```

::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
\@mrossde @Christian Pfeil zurück von 3.3 -> 3.2 und 3.3 -> 3.1 ?
oder kommt das später?

::::
:::

3.1 **Konzeptentwicklung und -validierung**: In dieser Phase werden Ideen und Konzepte für das neue Produkt generiert. Es können Marktanalysen durchgeführt, Kundenbedürfnisse ermittelt und Produktkonzepte skizziert werden. In dieser Phase werden auch die funktionalen und nicht-funktionalen Anforderungen des Produkts definiert. Es werden technische Spezifikationen erstellt und klare Ziele für das Produkt festgelegt.

3.2 **Entwurf und Entwicklung**: In dieser Phase wird das Produkt im Detail entworfen. Das umfasst die Erstellung von Konstruktionszeichnungen, das Festlegen von Materialien und Komponenten sowie das Erstellen von Prototypen für Tests und Bewertungen. Auch die Fertigungsprozesse für das spätere Produkt werden zumeist bereits in dieser Phase festgelegt (siehe → Produktions- und Werkstofftechnik).

3.3 **Prototypentwicklung und Test**: Es werden Prototypen des Produkts hergestellt, um seine Funktionalität und Leistung zu überprüfen. Diese Prototypen können in verschiedenen Iterationen verbessert werden, um das gewünschte Endprodukt zu erreichen. Teils bereits beginnend mit der Entwurfs- und Entwicklungsphase beginnen erste Tests, um frühestmöglich sicherzustellen, dass das spätere Produkt den zuvor definierten Anforderungen genügt. 

3.4 **Fertigungs- und Produktionsvorbereitung**: Spätestens ab beginn der Prototypenentwicklung beginnen die Vorbereitungen zur späteren (Serien-)produktion des Produkts. Dies beinhaltet die Auswahl von Lieferanten und die gesamte Planung der Produktion.

3.5 **Markteinführung und Vermarktung**: In dieser Phase wird das Produkt offiziell auf dem Markt eingeführt. Dies umfasst Marketing- und Vertriebsaktivitäten, um das Produkt zu bewerben und Kunden dafür zu gewinnen. Feedback und Rückmeldungen der Kunden werden gesammelt und legen die Grundlage für die Entwicklung von Aktualisierungen des laufenden Produkts oder für zukünftige Weiterentwicklungen des Produkts.