---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
---


<!-- -------------------------------------------------------------------------

                       Simultaneous Engineering

-------------------------------------------------------------------------- -->


## Simultaneous Engineering {#sec-se}

::: {.callout-tip}
## Definition: *"Simultaneous Engineering"*
Simultaneous Engineering (SE), auch als Parallel Engineering oder Concurrent Engineering bezeichnet, ist eine Produktentwicklungsmethode, die darauf abzielt, den traditionellen sequenziellen Ansatz (nacheinander) durch einen kooperativen und gleichzeitigen Ansatz zu ersetzen. Das Hauptziel des Simultaneous Engineering besteht darin, die Markteinführungszeit zu verkürzen, die Produktkosten zu senken und die Produktqualität zu steigern, indem verschiedene Phasen der Produktentwicklung parallel durchgeführt werden. 
:::

### Merkmale des Simultaneous Engineering

Die wesentlichen Merkmale des Simultaneous Engineering sind:

+ **Gleichzeitige Arbeit**: Im Gegensatz zum traditionellen sequenziellen Ansatz, bei dem jede Phase der Produktentwicklung nacheinander abgeschlossen wird (z. B. Design, Prototyping, Produktion), werden im Simultaneous Engineering verschiedene Phasen gleichzeitig bearbeitet. Dies ermöglicht eine erhebliche Zeitersparnis.

+ **Interdisziplinäre Teams**: Im Simultaneous Engineering arbeiten Teams aus verschiedenen Fachgebieten (z. B. Ingenieurwesen, Fertigung, Marketing, Qualitätssicherung) von Anfang an zusammen. Dies fördert die Kommunikation, den Informationsaustausch und die Kreativität.

+ **Frühe Einbeziehung aller Beteiligten**: Alle relevanten Parteien und Abteilungen werden von Anfang an in den Prozess einbezogen, um sicherzustellen, dass die Anforderungen und Bedenken aller berücksichtigt werden. Dies hilft, spätere Konflikte und Probleme zu vermeiden.

+ **Risikobewertung**: Risiken werden frühzeitig identifiziert und bewertet. Dies ermöglicht es, proaktiv Maßnahmen zu ergreifen, um potenzielle Probleme zu vermeiden oder zu mildern.

+ **Prototyping und schnelles Feedback**: Im Simultaneous Engineering werden Prototypen erstellt und getestet, um das Design und die Funktionalität des Produkts frühzeitig zu überprüfen. Dadurch können Änderungen vorgenommen werden, bevor das endgültige Produkt entwickelt wird.

+ **Kontinuierliche Verbesserung**: Der Ansatz des Simultaneous Engineering fördert eine Kultur der kontinuierlichen Verbesserung, bei der Teams ständig nach Möglichkeiten suchen, den Produktentwicklungsprozess zu optimieren und effizienter zu gestalten.

+ **Verkürzte Markteinführungszeit**: Eines der Hauptziele des Simultaneous Engineering ist die Beschleunigung der Markteinführung eines Produkts. Durch die gleichzeitige Durchführung von Aufgaben und die frühzeitige Identifizierung von Problemen kann das Produkt schneller auf den Markt gebracht werden.

+ **Kostenreduktion**: Durch die Identifizierung und Lösung von Problemen in frühen Phasen der Entwicklung können teure Änderungen in späteren Phasen vermieden werden. Dies trägt zur Senkung der Produktionskosten bei.

+ **Qualitätsverbesserung**: Die frühzeitige Identifizierung von Qualitätsproblemen und die kontinuierliche Überwachung und Verbesserung des Produkts tragen zur Steigerung der Produktqualität bei.

Simultaneous Engineering ist in Branchen wie dem Maschinenbau, der Automobilindustrie, der Elektronik und vielen anderen weit verbreitet. Es fördert eine effiziente und kooperative Herangehensweise an die Produktentwicklung, die dazu beiträgt, Produkte schneller, kostengünstiger und mit höherer Qualität auf den Markt zu bringen.

### SE-Partner

::: {.callout-tip}
## Definition: *"Simultaneous Engineering-Partner"*
Simultaneous Engineering-Partner ("SE-Partner") sind externe Unternehmen, die bei "Simultaneous Engineering" durch Übernahme von verschiedenen Aufgabenstellungen das Produktentstehungsprojekt unterstützen.
:::

Die SE-Partner können in diesem Kontext verschiedene Aufgaben und Rollen übernehmen, um die Prinzipien des Simultaneous Engineering umzusetzen:

+ **Entwicklung von Teilsystemen oder Komponenten**: SE-Partner können für die Entwicklung und Gestaltung bestimmter Teilsysteme, Baugruppen oder Komponenten verantwortlich sein, während andere Teams gleichzeitig an anderen Teilen des Produkts arbeiten.

+ **Prototypenherstellung und -test**: Ein SE-Partner könnte für die Herstellung von Prototypen verantwortlich sein, um frühzeitig Tests und Überprüfungen durchzuführen, um sicherzustellen, dass das Design den Anforderungen entspricht.

+ **Materialbeschaffung und Lieferkette**: Die Beschaffung von Materialien und die Organisation der Lieferkette sind kritische Aspekte der Produktentwicklung. SE-Partner können dabei helfen, sicherzustellen, dass die erforderlichen Materialien rechtzeitig verfügbar sind.

+ **Qualitätskontrolle und -sicherung**: SE-Partner können Qualitätskontrollen und -sicherungsmaßnahmen implementieren, um sicherzustellen, dass die hergestellten Teile den Qualitätsstandards entsprechen.

+ **Datenmanagement und Kommunikation**: Eine effektive Kommunikation und das Teilen von Daten zwischen verschiedenen Teams und Abteilungen sind entscheidend für den Erfolg des Simultaneous Engineering. SE-Partner können dazu beitragen, Daten zu verwalten und den Informationsaustausch zu erleichtern.

+ **Projektmanagement**: SE-Partner können Projektmanagementdienstleistungen anbieten, um sicherzustellen, dass alle Aktivitäten im Rahmen des Simultaneous Engineering gut koordiniert und überwacht werden.

Die Zusammenarbeit mit SE-Partnern im Rahmen des Simultaneous Engineering kann die Effizienz und Geschwindigkeit der Produktentwicklung in einem Unternehmen erheblich steigern. 

Indem verschiedene Aspekte des Designs, der Herstellung und der Qualitätssicherung gleichzeitig berücksichtigt werden, kann die Markteinführungszeit verkürzt und die Wettbewerbsfähigkeit gesteigert werden. Die genaue Rolle und Verantwortlichkeit der SE-Partner können je nach den Anforderungen und Zielen des Produktentwicklungsprojekts variieren.

### Entwicklungsdienstleister

::: {.callout-tip}
## Definition: *"Entwicklungsdienstleister"*
Entwicklungsdienstleister (auch als Engineering-Dienstleister oder EDL bezeichnet) sind externe Unternehmen, die auf die Bereitstellung von technischen Dienstleistungen und Expertise in der Produktentwicklung, Konstruktion und Ingenieurwissenschaft spezialisiert sind.
:::

Entwicklungsdienstleister arbeiten oft in Partnerschaft mit anderen Unternehmen, um bei der Konzeption, Entwicklung und Optimierung von Produkten, Systemen oder Lösungen zu helfen. Die Dienstleistungen eines Entwicklungsdienstleisters sind oft hochspezialisiert und können in verschiedenen Bereichen und Branchen in Anspruch genommen werden und umfassen in der Regel:

+ **Produktdesign und -entwicklung**: Entwicklungsdienstleister können bei der Konzeption neuer Produkte oder der Verbesserung bestehender Produkte unterstützen. Dies kann die Erstellung von Produktkonzepten, technischen Zeichnungen, Prototypen und Testdurchführung bis hin zur eigenständigen kompletten Entwicklung einzelner Komponenten eines Produkts umfassen.

::: {.callout-important}
Entwicklungsdienstleister können, müssen aber nicht notwendigerweise spätere Lieferanten der vom Entwicklungsdienstleister entwickelten Komponenten sein!
:::

+ **Technische Beratung**: Entwicklungsdienstleister bieten technische Expertise und Beratung in verschiedenen Ingenieurdisziplinen, um Unternehmen bei technischen Herausforderungen zu unterstützen und innovative Lösungen zu finden.

+ **Simulation und Modellierung**: Entwicklungsdienstleister sind oft hoch spezialisiert und verfügen über Software und Tools, um Simulationen und Modelle von Produkten oder Systemen zu erstellen. Dies hilft dabei, das Verhalten und die Leistung im Voraus zu analysieren und zu optimieren.

+ **Forschung und Entwicklung**: Sie können bei der Durchführung von Forschungs- und Entwicklungsprojekten in Zusammenarbeit mit Kundenunternehmen helfen, um neue Technologien und Produkte zu entwickeln.

+ **Prototyping und Testing**: Entwicklungsdienstleister unterstützen bei der Erstellung von Prototypen, Testplänen und Tests, um die Produktqualität sicherzustellen und Probleme frühzeitig zu erkennen und zu beheben.

+ **Materialauswahl und Lieferantenmanagement**: Sie können bei der Auswahl geeigneter Materialien für Produkte und bei der Lieferantenmanagement unterstützen.

+ **Projektmanagement**: Einige Entwicklungsdienstleister bieten auch Projektmanagementdienstleistungen an, um dabei zu unterstützen dass Projekte im Zeit- und Kostenrahmen abgeschlossen werden.

Entwicklungsdienstleister sind in vielen Branchen und Industriezweigen weit verbreitet, darunter Automobil, Luft- und Raumfahrt, Elektronik und dem Maschinenbau. Sie können eine wichtige Rolle spielen, um Unternehmen bei der Bewältigung von technischen Herausforderungen, der Beschleunigung der Produktentwicklung und der Senkung der Entwicklungskosten zu unterstützen. 

Unternehmen nutzen Entwicklungsdienstleister, um zeitlich befristet auf zusätzliche oder hochspezialisierte Ressourcen und spezifisches Fachwissen zuzugreifen, insbesondere wenn sie nicht über die internen Ressourcen oder das für die Produktentwicklung erforderliche Fachwissen verfügen.

<!--
Entwicklungsdienstleister (Engineering-Dienstleister (EDL)) und Simultaneous Engineering-Partner (SE-Partner) sind beide Akteure, die in den Bereich der Produktentwicklung und Ingenieurwissenschaften involviert sind, aber sie haben unterschiedliche Schwerpunkte und Aufgaben in diesem Kontext. Hier sind die Hauptunterschiede zwischen den beiden:

1. **Fokus und Dienstleistungen**:

`   `- \*\*Entwicklungsdienstleister (EDL):\*\* Entwicklungsdienstleister sind in erster Linie auf die Bereitstellung von technischen Dienstleistungen und Ingenieurberatung spezialisiert. Sie bieten eine breite Palette von Dienstleistungen, die von Produktdesign und -entwicklung bis hin zu technischer Beratung und Prototyping reichen. EDLs konzentrieren sich darauf, technische Lösungen für Kundenprojekte zu entwickeln oder bestehende Produkte zu verbessern.

`   `- \*\*Simultaneous Engineering-Partner (SE-Partner):\*\* SE-Partner sind auf die Umsetzung des Konzepts des Simultaneous Engineering spezialisiert, bei dem verschiedene Phasen der Produktentwicklung parallel durchgeführt werden, um die Markteinführungszeit zu verkürzen und die Produktqualität zu steigern. Ihr Fokus liegt auf der Koordinierung und Umsetzung dieses Ansatzes, der eine effizientere Entwicklung ermöglichen soll.

2\. \*\*Arbeitsweise und Koordination:\*\*

`   `- \*\*Entwicklungsdienstleister (EDL):\*\* EDLs arbeiten in der Regel auf Projektbasis und bieten spezifische technische Dienstleistungen für Kundenprojekte an. Sie können in der Entwicklung eines Teils oder Aspekts eines Produkts eingebunden sein, während andere Aspekte von internen Teams des Kunden entwickelt werden.

`   `- \*\*Simultaneous Engineering-Partner (SE-Partner):\*\* SE-Partner arbeiten oft als strategische Partner, die den gesamten Entwicklungsprozess eines Produkts oder Systems koordinieren und sicherstellen, dass verschiedene Teams und Abteilungen parallel arbeiten und effektiv kommunizieren.

3\. \*\*Zusammenarbeit und Integration:\*\*

`   `- \*\*Entwicklungsdienstleister (EDL):\*\* EDLs arbeiten in der Regel in enger Zusammenarbeit mit internen Teams des Kunden, bieten jedoch spezialisierte Dienstleistungen und Expertise an. Sie sind oft externe Berater oder Auftragnehmer.

`   `- \*\*Simultaneous Engineering-Partner (SE-Partner):\*\* SE-Partner spielen eine aktivere Rolle bei der Integration verschiedener Teams und Abteilungen innerhalb des Kundenunternehmens, um sicherzustellen, dass das Konzept des Simultaneous Engineering vollständig umgesetzt wird.

4\. \*\*Verantwortlichkeiten und Ziele:\*\*

`   `- \*\*Entwicklungsdienstleister (EDL):\*\* EDLs sind dafür verantwortlich, die ihnen zugewiesenen Aufgaben in einem Projekt zu erfüllen und die spezifischen Ziele und Anforderungen des Kunden zu erfüllen.

`   `- \*\*Simultaneous Engineering-Partner (SE-Partner):\*\* SE-Partner sind verantwortlich für die Umsetzung des Simultaneous Engineering-Konzepts und das Erreichen der damit verbundenen Ziele, wie die Beschleunigung der Markteinführung und die Verbesserung der Produktqualität durch die Koordination paralleler Aktivitäten.

In vielen Fällen können Entwicklungsdienstleister und Simultaneous Engineering-Partner in einem Projekt zusammenarbeiten. Ein Entwicklungsdienstleister kann beispielsweise spezifische technische Dienstleistungen für einen Teil des Projekts bereitstellen, während ein SE-Partner die Gesamtkoordination und Implementierung des Simultaneous Engineering-Ansatzes übernimmt. Die genaue Rolle und Verantwortung können jedoch je nach den Anforderungen des Projekts und den Zielen des Kunden variieren.
-->
