---
format:
  html:
    embed-resources: true
lang: de
bibliography: Literatur.bib
---

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
  - SMARTe Ziele
  - Goodharts Gesetz
  - KPIs
copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
-->



<!-- -------------------------------------------------------------------------

                       SMARTe Ziele

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Grundlagen
## Methodische Grundlagen
:::

### SMARTe Ziele {#sec-smart}

[SMART](https://de.wikipedia.org/wiki/SMART_(Projektmanagement)) ist ein [Akronym](https://de.wikipedia.org/wiki/Akronym) und gleichzeitig eine Sammlung von Kriterien zur eindeutigen Formulierung von **mess- und überprüfbaren Zielen**.

Um Ziele [SMART](https://de.wikipedia.org/wiki/SMART_(Projektmanagement)) zu formulieren, sind bei deren Formulierung **jede** der fünf folgenden Anforderungen zu berücksichtigen:

```{mermaid}
%%| label: fig-label-mmsmart
%%| fig-cap: "Anforderungen an SMARTe Ziele"
%%| echo: false
%%{init: {'theme': 'forest'}}%%
mindmap
  root((SMARTe Ziele))
    (Spezifisch)
    (Messbar)
    (Attraktiv)
    (Relevant)
    (Terminiert)
```


1. **Spezifisch (Specific)**: Das Ziel muss klar und präzise definiert sein, damit alle Beteiligten ein einheitliches Verständnis davon haben.

2. **Messbar (Measurable)**: Es muss möglich sein, den Fortschritt und das Erreichen des Ziels anhand quantitativer oder qualitativer Kriterien zu messen.

3. **Attraktiv/Erreichbar (Achievable)**: Das Ziel soll anspruchsvoll sein, aber dennoch realistisch und erreichbar, basierend auf den verfügbaren Ressourcen und Fähigkeiten.

4. **Relevant (Relevant)**: Das Ziel muss mit den übergeordneten Zielen und der langfristigen Vision der Organisation in Einklang stehen.

5. **Terminiert/Zeitgebunden (Time-bound)**: Es ist wichtig, einen klaren Zeitrahmen oder ein Fälligkeitsdatum festzulegen, um sicherzustellen, dass das Ziel innerhalb eines bestimmten Zeitraums erreicht wird.

Ziele SMART zu formulieren erhöht die Wahrscheinlichkeit, dass die Ziele von allen Mitarbeitenden klar verstanden werden, motivierend wirken und somit effektiv zur Leistungssteigerung sowohl von einzelnen Personen, aber auch von  Projektteams beitragen.

::: {.callout-caution}
## Tipp!
Das Setzen von [SMARTen Zielen](https://de.wikipedia.org/wiki/SMART_(Projektmanagement)) zu Beginn eines Semesters kann dem geneigten Leser helfen, während des Semesters fokusiert zu bleiben. Beispiel für ein SMARTes Ziel: *"Mein Ziel ist es, die Vorlesung und Labore am Ende des Semesters mit mindestens der Note 2,3 bestanden zu haben."*
:::


#### Exkurs: Goodharts Gesetz

[SMARTe Ziele](https://de.wikipedia.org/wiki/SMART_(Projektmanagement)) (spezifisch, messbar, attraktiv, realistisch und terminiert) sind in der heutigen Welt allgegenwärtig. Sie dienen als Maßstab für den Erfolg sowohl von Unternehmen als auch unseren individuellen Fortschritten. Doch Vorsicht ist geboten! So warnt [Goodharts Gesetz](https://de.wikipedia.org/wiki/Goodharts_Gesetz) in seiner populären kurzen Fassung:

---

> *"Wird eine Messgröße zum Ziel, hört sie auf, eine gute Messgröße zu sein."*

---

Diese generalisierte Erkenntnis, die im Kern auf den britischen Ökonomen [Charles Goodhart](https://en.wikipedia.org/wiki/Charles_Goodhart) zurückgeht, weist auf die Gefahr hin, die entsteht, wenn Indikatoren selbst zu festen Zielen werden, sprich wenn sich alles mehr um die Messgröße dreht als um das dahinter liegende Ziel bzw. die Problemlösung.


::: {.content-visible unless-meta="kommentare.off"}

:::: {style="background-color: #9affa4"}
\@mrossde Rücksprache Christian -> KPIs in Unternehmen sind ja Ziele, oder wie ist das gemeint mit der Kenngröße, wenn Sie zum Ziel wird? Sie ist ja Teil des Ziels?

::::
:::

<!--
^[Ein Beispiel aus Hanoi, als dieses noch unter französischer Kolonialherrschaft stand, veranschaulicht die Problematik. Im Bemühen, eine Rattenplage zu bekämpfen, führte das Regime 1902 das Prinzip ein, dass die Menschen eine Prämie erhielten, wenn sie für jede erlegte Ratte einen abgetrennten Rattenschwanz abgaben. Irgendwann allerdings wurden Ratten ohne Schwänze entdeckt. Vietnamesische Rattenfänger fingen die Ratten ein, schnitten ihnen die Schwänze ab und entließen sie dann wieder in die Freiheit, damit sie sich weiter vermehren konnten – um ihnen ein höheres Einkommen zu bescheren.]
-->

Goodharts Gesetz ist eine wichtige Warnung, dass die starre Überbetonung einzelner Indikatoren zu unerwünschten Ergebnissen führen kann.  Flexible und vielfältige Bewertungsmethoden, die unterschiedliche Aspekte berücksichtigen, können hier einen Ausweg bieten.


In einer Welt, in der Daten und Metriken eine immer wichtigere Rolle spielen, kann das Festhalten an starren Messgrößen (z.B. → [Key-Performance-Indicators (KPIs)](https://de.wikipedia.org/wiki/Key-Performance-Indicator)) den Blick auf das eigentliche Ziel verstellen. 

{{< include KPI.qmd >}}

::: {.callout-caution}
## Erfahrungen aus der Praxis
Maßnahmen, die alleine die Ziel dienen, eine Messgröße zu erreichen, statt das ursprüngliche Problem zu lösen, sind bedeutungslos, oft sogar kontraproduktiv.
::: 

Goodharts Gesetz ist eine freundliche Erinnerung bei Entscheidungen nicht nur das formale SMARTe Ziel, sondern auch den Gesamtkontext immer mit zu berücksichtigen.
