

<!--
headlines:
  off: true
extended-content:
  off: false
included-content:
  off: false
worksheets:
  off: true
-->

<!--
title: "DEB Produktentwicklung"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung"* für den Studiengang Digital Engineering DEB
keywords:
  - Stochastik

copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: true
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 0
link-external-icon: true
link-external-newwindow: true
-->

<!--
number-offset: 
0 Grundlagen
1 Ideenfindung und Konzeptentwicklung
2 Entwurfs- und Entwicklungsphase
3 Prototyping und Test
4 Produktionsplanung und Produktion
5 Softskills
6 Literatur 
7 Anhang
-->

<!-- -------------------------------------------------------------------------

                       Begriffe

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Grundlagen
## Begriffe
:::

<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
<!--
::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::
-->

### Stochastik {#sec-stochastik}

::: {.callout-tip}
## Begriffsklärung *"Stochastik"*
Die [Stochastik](https://de.wikipedia.org/wiki/Stochastik) (*"Kunst des Vermutens"*) ist die Mathematik des Zufalls oder die Mathematik der Daten und des Zufalls und fasst als Oberbegriff die Gebiete [Wahrscheinlichkeitstheorie](https://de.wikipedia.org/wiki/Wahrscheinlichkeitstheorie) und [mathematische Statistik](https://de.wikipedia.org/wiki/Mathematische_Statistik) zusammen.

Die Wahrscheinlichkeitstheorie stellt die Begriffe zur mathematischen Modellierung von Vorgängen bereit, in denen zufällige Ereignisse auftreten. Auf dieser Grundlage liefert die mathematische Statistik Verfahren, um aus Beobachtungsdaten Modellparameter zu bestimmen und Aussagen über die Angemessenheit der Modellierung machen zu können.
:::



### Wahrscheinlichkeitstheorie

::: {.callout-tip}
## Begriffsklärung *"Wahrscheinlichkeitstheorie"*
Die [Wahrscheinlichkeitstheorie](https://de.wikipedia.org/wiki/Wahrscheinlichkeitstheorie), auch Wahrscheinlichkeitsrechnung oder Probabilistik, ist ein Teilgebiet der Mathematik, das aus der Formalisierung, der Modellierung und der Untersuchung von Zufallsgeschehen hervorgegangen ist. Gemeinsam mit der mathematischen Statistik, die anhand von Beobachtungen zufälliger Vorgänge Aussagen über das zugrunde liegende Modell trifft, bildet sie das mathematische Teilgebiet der Stochastik. Die zentralen Objekte der Wahrscheinlichkeitstheorie sind zufällige Ereignisse, Zufallsvariablen und stochastische Prozesse.
:::


```{mermaid}
%%| fig-width: 6.4
%%| label: fig-label-stochastik
%%| fig-cap: "Begriffe zur Stochastik"
graph TD
    SK["Stochastik"]
    MS["Mathematische Statistik"]
    WT["Wahrscheinlichkeitstheorie"]
   
    SK --> MS
    SK --> WT
```

<!--
  style x fill:#a00,stroke:#000,color:#fff
  style y fill:#ff7e00,stroke:#000,color:#fff
-->