---
title: "MTB3 Entwicklung mechatronischer Systeme 1"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    email: christian.anders@hs-esslingen.de
    affiliations: Hochschule Esslingen
date: last-modified
toc: false
number-sections: false
scrollable: true
---

<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
::: {.callout-warning}
## WARNING!
**THIS DOCUMENT IS STILL WORK IN PROGRESS!!!**
:::

<!-- -------------------------------------------------------------------------

                       Aufgabe: Auswahl Dateiformat

-------------------------------------------------------------------------- -->

| Kriterium            | HTML     | PDF ($\LaTeX$) | Print2PDF | Word (*.docx) |
|----------------------|----------|----------|----------|----------|
| Kriterium 1          |          |          |          |          |
| Kriterium 2          |          |          |          |          |
| Kriterium 3          |          |          |          |          |
| Kriterium 4          |          |          |          |          |
| Kriterium 5          |          |          |          |          |
| **Summe**:           |          |          |          |          |

: Bewertungsmatrix zur Auswahl des Dateiformats für das Skript zur Vorlesung {#tbl-bewertungsmatrix .striped .hover .bordered tbl-colwidths="[28,18,18,18,18]"}


::: {#nte-auswahlformat .callout-note}
## Bewertungsmatrix zur Auswahl des Dateiformats für das Skript zur Vorlesung (Dauer (20 min)

**Ausganssituation**: Ihr Dozent erstellt das Skript zur Vorlesung mittels Quarto im Format HTML. Bei Bedarf bietet Ihr Dozent an, neben HTML ein weiteres Dateiformat zur Verfügung zu stellen, sofern dafür aus der Gruppe eine überzeugende Begründung vorliegt.

**a)** Erarbeiten Sie in der Gruppe die Bewerungskritieren, die im Hinblick auf das Dateiformat für Sie wichtig sind.

Vorgaben:

+ Nehmen Sie sich hierzu 10 Minuten Zeit. Sollten Sie mehr als fünf Kriterien erarbeiten erweitern wir die Matrix zum zusätzliche Zeilen; bei weniger als fünf Kritieren entfernen wir die leeren Zeilen aus der Matrix.
+ Achten Sie darauf, dass die Kriterien voneinander unabhängig sind, so dass eine versteckte Über- oder Untergewichtung eines einzelnen Aspekts vermieden wird.
 
**b)** Bewerten Sie die möglichen vier Dateiformate. Gehen Sie dafür Zeile für Zeile vor und treffen Sie eine Bewertung für jedes der vier Dateiformate.

Vorgaben:

+ Die Bewertungen reichen von 1 bis 5, wobei 1 die schlechteste Bewertung und 5 die beste Bewertung ist. Bitte achten Sie darauf die Bewertungsspanne von 1 bis 5 möglichst vollständig auszunutzen.

**c)** Ermitteln Sie das Ergebnis Ihrer Bewertung durch Aufsummieren der Einzelbewertungen für jedes der vier Dateiformate.

**d)** Bitte Reflektieren Sie zum Abschluss noch kurz gemeinsam in der Gruppe: 

+ Entspricht das Ergebnis Ihren Erwartungen? 
+ Können Sie das gefundene Ergebnis nachvollziehen? 
+ Sind Sie persönlich mit dem Vorgehen zur Entscheidungsfindung zufrieden?
:::
