---
title: "DEB3 Produktentwicklung 1"
format:
  html:
    embed-resources: true

author:
  - name: "Christian Anders"
    degrees: 
    roles: "Dozent"
    email: christian.anders@hs-esslingen.de
    affiliation: 
      - name: "Hochschule Esslingen"
        department: "Wirtschaft & Technik"
        group: "Digital Engineering (DEB)"
        city: "Esslingen am Neckar"
        postal-code: 73728
        country: "Deutschland"
        url: https://www.hs-esslingen.de/
abstract: > 
  Skript zur Vorlesung und Labor *"Produktentwicklung 1"* für den Studiengang Digital Engineering DEB3
keywords:
  - Produktentstehungsprozess
  - Entwicklungsmethodik
  - Prototyping und Test
  - Anforderungen
copyright: 
  holder: Christian Anders
  year: 2025
lang: de
bibliography: Literatur.bib
date: last-modified
toc: false
number-sections: true
scrollable: true
toc-location: right
cap-location: bottom
number-offset: 3
link-external-icon: true
link-external-newwindow: true
---

<!-- -------------------------------------------------------------------------

                       Anforderungen Testing

-------------------------------------------------------------------------- -->

::: {.content-visible unless-meta="headlines.off"}
# Prototyping und Test
## Testing
:::


<!-- -------------------------------------------------------------------------

                       Ziele von Tests

-------------------------------------------------------------------------- -->


```{mermaid}
%%| label: fig-label-mmzieletesting
%%| fig-cap: "Mindmap wichtiger Ziele beim Testing"
%%{init: {'theme': 'forest'}}%%
mindmap
  root(Ziele Testing)
    Ziel1(Fehleridentifikation)
      Beschreibung(Probleme und Bugs im Produkt erkennen)
    Ziel2(Validierung)
      Beschreibung(Sicherstellen, dass das Produkt den Anforderungen entspricht)
    Ziel3(Verifizierung)
      Beschreibung(Überprüfung der technischen Spezifikationen)
    Ziel4(Leistungsbewertung)
      Beschreibung(Leistung des Produkts unter verschiedenen Bedingungen testen)
    Ziel5(Benutzerakzeptanz)
      Beschreibung(Feedback von Endbenutzern einholen)
    Ziel6(Sicherheit)
      Beschreibung(Sicherheitslücken und Schwachstellen identifizieren)
```

<!-- -------------------------------------------------------------------------

                       Grundlegende Begriffe

-------------------------------------------------------------------------- -->
### Grundlegende Begriffe

::: {.callout-tip}
## Definition: *"Teststrategie"*
Eine [Teststrategie](https://de.wikipedia.org/wiki/Softwaretest#Teststrategie) ist ein übergeordneter **Plan**, der die **Vorgehensweise, Methoden und Ziele** für das Testen eines Produkts definiert. Die Teststrategie legt fest, **welche Testarten, Testumfänge, Werkzeuge und Qualitätskriterien** angewendet werden, um sicherzustellen, dass das Produkt die Anforderungen erfüllt und fehlerfrei funktioniert.  
:::

Die Teststrategie dient als **Richtlinie** für das Testteam und stellt sicher, dass die Tests effizient, nachvollziehbar und reproduzierbar durchgeführt werden. Sie umfasst typischerweise Aspekte wie **Testziele, Teststufen, Automatisierungsgrad, Testumgebungen, Risikobetrachtung** sowie **Dokumentation** und **Berichterstattung**.



<!-- -------------------------------------------------------------------------

                       Anforderungen an Tests

-------------------------------------------------------------------------- -->
### Anforderungen an Tests {#sec-anforderungen_an_tests}

Die folgende Mindmap fasst die **grundsätzlichen Anforderungen an Tests** in der Prototyping- und Testphase zusammen. Diese Anforderungen sind bei der Erarbeitung der Teststrategie zu berücksichtigen.

```{mermaid}
%%| label: fig-label-mmanforderungentests
%%| fig-cap: "Mindmap wichtiger Anforderungen an Test in der Phase Prototyping und Test"
%%{init: {'theme': 'forest'}}%%
mindmap
  root(Anforderungen an Test)
    (Automatisierbarkeit)
    (Reproduzierbarkeit)
    (Skalierbarkeit)
    (Messbarkeit)
    (Realitätsnähe)
    (Nachvollziehbarkeit)
    (Sicherheit)
    (Effizienz)
    (Modularität)
    (Flexibilität)
```





Um die Qualität und Effizienz des Testprozesses zu verbessern wird das Automatisieren von Tests angestrebt. 
Folgende Ziele werden mit der Automatisierung von Tests verfolgt:

```{mermaid}
%%| label: fig-label-mmzieleautomatisiertetests
%%| fig-cap: "Mindmap wichtiger Ziele beim Automatisieren von Tests"
%%{init: {'theme': 'forest'}}%%
mindmap
  root(Ziele der Automatisierung von Tests)
    Ziel1(Effizienzsteigerung)
      Beschreibung(Reduzierung der Testdurchführungszeit)
    Ziel2(Kostensenkung)
      Beschreibung(Langfristige Verringerung der Testkosten)
    Ziel3(Fehlerreduktion)
      Beschreibung(Minimierung menschlicher Fehler)
    Ziel4(Kontinuität)
      Beschreibung(Ermöglichung kontinuierlicher Tests)
    Ziel5(Skalierbarkeit)
      Beschreibung(Möglichkeit, Tests schnell zu erweitern)
    Ziel6(Wiederholbarkeit)
      Beschreibung(Konsistente und reproduzierbare Testergebnisse)
```



<!--
Automatisierbarkeit
      - Skalierbarkeit
      - Wiederholbarkeit
    Reproduzierbarkeit
      - Konsistente Ergebnisse
      - Unabhängig von Testumgebung
    Skalierbarkeit
      - Tests auf verschiedene Produktversionen anwendbar
      - Anpassbar für größere Testumfänge
    Messbarkeit
      - Klare Metriken und KPIs
      - Objektive Bewertungskriterien
    Realitätsnähe
      - Simulation realer Nutzungsbedingungen
      - Berücksichtigung von Störfaktoren
    Nachvollziehbarkeit
      - Detaillierte Dokumentation
      - Klare Testprotokolle
    Sicherheit
      - Identifikation von Risiken
      - Absicherung gegen Fehlfunktionen
    Effizienz
      - Schnelle Durchführung
      - Minimaler Ressourcenverbrauch
    Modularität
      - Tests unabhängig voneinander durchführbar
      - Austauschbarkeit einzelner Testkomponenten
    Flexibilität
      - Anpassbarkeit an sich ändernde Anforderungen
      - Erweiterbarkeit für neue Funktionen
-->





<!-- -------------------------------------------------------------------------

                       ab hier alter Textbaustein als Vorlage :-)

-------------------------------------------------------------------------- -->









<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
<!--
::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::
-->

<!-- -------------------------------------------------------------------------

                       Automatisieren von Tests

-------------------------------------------------------------------------- -->
<!--
### Automatisieren von Tests

(siehe → Vorlesung **DEB5 Produktentwicklung 2**)
-->
<!-- -------------------------------------------------------------------------

                       Callout !!! WARNING !!!

-------------------------------------------------------------------------- -->
<!--
::: {.callout-warning}
## WARNING!
**THIS CHAPTER IS STILL WORK IN PROGRESS!!!**
:::
-->