Von zentraler Bedeutung für ein erfolgreiches Projektmanagement ist der oben bereits genannte Aspekt der Weisungs- und Entscheidungsbefugnis als eine Ausprägung der Kompetenz einzelner Projektbeteiligter. Hierbei handelt es sich um eine Führungsaufgabe. Weisungs- und Entscheidungsbefugnis bezieht sich auf die autorisierte Fähigkeit einer Person, Anweisungen zu geben und Entscheidungen zu treffen, die für die Ausführung einer Aufgabe oder die Erreichung eines Projektziels erforderlich sind. **Diese Kompetenz kann zeitlich befristet einer Person zugewiesen werden und hat Priorität über die in einem Unternehmen etablierte Führungshierarchie.**




::: {.callout-caution}
## Tipp!
Bei der in Projekten befristet zugewiesenen Weisungs- und Entscheidungsbefugnis handelt es sich in der Regel um *„geliehene Macht“*. Diese befristet zugewiesenen Befugnisse können gleichwohl sehr weitreichenden Einfluss auf die Arbeiten einiger oder auch sehr vieler Projektbeteiligter haben. Es ist in höchstem Maße ratsam, sich nicht dem *„Rausch der Macht“* hinzugeben, sondern im Gegenteil, mit maximaler Aufmerksamkeit und Energie auf eine faire und kooperative Zusammenarbeit im Projekt hinzuwirken.
:::

Die zugewiesene Kompetenz der Weisungs- und Entscheidungsbefugnis beinhaltet das Recht und die Verantwortung: 

- anderen, definierten Projektmitarbeitern Anweisungen erteilen  
- Aufgaben zuweisen  
- klare Richtlinien und Leitlinien geben  
- Kontrolle über bestimmte Aspekte eines Projekts oder einer Aufgabe übernehmen  
- Durchführung von Aktivitäten lenken  
- Entscheidungen treffen, die für den Fortschritt des Projekts von Bedeutung sind  
- zwischen verschiedenen Optionen abwägen  
- Risiken bewerten  
- strategische, operative oder technische Aspekte berücksichtigen  
- Autorität ausüben  
- sicherstellen/ kontrollieren, dass die zugewiesenen Aufgaben ordnungsgemäß ausgeführt werden  


Die Entscheidungsbefugnis kann sich auf strategische, operative oder technische Aspekte beziehen und kann sowohl Einzelpersonen als auch Teams gewährt werden. Die Kompetenz der Weisungs- und Entscheidungsbefugnis spielt eine wichtige Rolle bei der effektiven Leitung und Steuerung von Projekten.

::: {.callout-caution}
Grundsätzlich sind die AKV aller Projektbeteiligten **VOR** Projektbeginn zu klären jeweils den von den AKV betroffenen Projektbeteiligten klar zu kommunizieren.
:::