name: source code checks
on:
  push:
  pull_request:
jobs:
  python-check:
    runs-on: [ os-small-amd64-linux ]
    steps:
      - uses: actions/checkout@v3
      - id: setup-rye
        uses: eifinger/setup-rye@v3
        with:
          enable-cache: true
          cache-prefix: 'rye'
      - run: rye sync
      - run: rye lint
      - run: rye run pyright
      - run: rye test

